### ISSUE TITLE
Rules around 'username' don't match across AMO and FxA

### ISSUE THREAD

**Issue by krupa** [mozilla/olympia#1000]
## steps to reproduce
1. Go to https://addons-dev.allizom.org/en-US/firefox/
2. Click on Register
3. Sign up with an account with the format: user.name+0@gmail.com
4. Validate the account as needed
5. Navigate to Go to My Profile -> Edit Profile
6. Save changes

## expected behavior:
username which is generated by default shouldn't throw errors.

## observed behavior
Saving the form fails with "Enter a valid username consisting of letters, numbers, underscores or hyphens."

**Comment by wagnerand** [comment]
Off-topic: Congrats to #1000!
