### ISSUE TITLE
Change password feature in AMO doesn't work with FxA

### ISSUE THREAD

**Issue by krupa** [mozilla/olympia#1002]
## steps to reproduce:
1. Register with FxA on AMO-dev
2. After signing in, navigate to My Profile -> Edit Profile
3. Click on Change Password
4. Update to your new password
5. Log out
6. Try to sign in with your new password

## expected behavior:
- If we allow changing password on AMO, the password change gets reflected in FxA OR password change link loads the appropriate form on FxA
- Password change is successful

## actual behavior:
- password change is unsuccessful

**Comment by andymckay-limited-access** [comment]
If you are on FxA we should redirect you over to FxA and let them handle it.

**Comment by mstriemer** [comment]
I think Marketplace doesn't have any password change link at all. I'm not sure we'd be able to send them to change their password for a specific account.

For example I'm currently signed in to addons-dev with my personal email and marketplace-dev with my work email but going to https://stable.dev.lcip.org/settings/change_password shows my personal account so the link would work on addons-dev but not marketplace-dev. A bit confusing.

Perhaps the best we can do is link to documentation which makes me wonder if we should bother at all.

**Comment by andymckay** [comment]
Ugh that is confusing. I don't know if the FxA team can recommend something here? @ryanfeeley

**Comment by ryanfeeley** [comment]
@andymckay For FxA users, you'd hide the Change Password and Change Email fields and instead add a link to Manage Firefox Account that links to that user’s FxA Settings. The link would include their email and would look something like:
https://accounts.firefox.com/settings?uid=8d41478afbc11a87f6c3943d&email=ryanfeeley%40gmail.com&entrypoint=addons

**Comment by mstriemer** [comment]
Ah, cool. I tried passing email but that wasn't enough. That looks pretty good.

**Comment by ryanfeeley** [comment]
Something like: 
<img width="594" alt="manage" src="https://cloud.githubusercontent.com/assets/68213/11516548/e3a8c76c-9851-11e5-8c67-df0f88123772.png">

**Comment by andymckay** [comment]
Sounds good, thanks.
