### ISSUE TITLE
Update the copy regarding unsigned add-ons

### ISSUE THREAD

**Issue by krupa** [mozilla/olympia#1010]
## steps to reproduce:
1. Load https://addons.allizom.org/en-US/developers/addon/submit/2
2.  Notice the warning copy under the checkbox for unlisted add-ons

## observed behavior:
Since we now sign all unlisted add-ons, the copy needs to be updated.

## screenshot:
https://www.dropbox.com/s/214tc1ikkcxlaen/Screenshot%202015-12-01%2012.12.56.png?dl=0

**Comment by andymckay** [comment]
Would be nice to get in before the tag if that's possible.

**Comment by magopian** [comment]
Touching this part of the code is tricky, and should be thoroughly QA tested, not sure we want that on such a short notice
