### ISSUE TITLE
Layout issue in queue page when containing a long-name Add-on

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/olympia#1019]
Steps to reproduce:
1. Sign in to AMO stage Developer Hub page https://addons.allizom.org/en-US/developers/
2. Submit an Add-on with a long name (i.e. https://addons.allizom.org/en-US/developers/addon/longnaaaaaaaaaaaaaaaaaaaaaaaaa/edit )
3. Go to Editor Tools and observe the queue where the “long-name” Add-on is listed

Expected results:
The page has no display or layout issues.

Actual results:
The page has layout issues.

Notes/Issues:
Verified on FF42(Win 7). Issue is reproducing on AMO-stage and AMO-dev.
Screenshot for this issue: 
![2015-12-02_1710](https://cloud.githubusercontent.com/assets/15685960/11535833/54e094ba-991e-11e5-83ad-bb9405d9db71.png)

**Comment by andymckay** [comment]
I don't think we'll get to this to be honest until we get to rewrite the reviewer tools.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-04-08_1051](https://cloud.githubusercontent.com/assets/15685960/14377424/31ae4ad2-fd78-11e5-875a-d5a65bffda1b.png)
