### ISSUE TITLE
Improve signing API for pass/fail detection in `jpm sign`

### ISSUE THREAD

**Issue by kumar303** [mozilla/olympia#1021]
We have some crazy if branching in jpm sign to detect pass/fail/needs-review. We can improve the API response to simplify this. Here is an example: https://github.com/mozilla-jetpack/jpm/pull/408

**Comment by andymckay** [comment]
This has changed quite a bit since then, this still valid @kumar303?

**Comment by kumar303** [comment]
Yeah, I think so. I see at least the `automated_signing` key which will help. I'll close for now until we think of something more specific that's needed.
