### ISSUE TITLE
Web Extensions shouldn't be automatically signed when submitted as an unlisted add-on

### ISSUE THREAD

**Issue by krupa** [mozilla/olympia#1029]
## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/developers/addon/submit/2
2. Select the option to submit your add-on as "unlisted"
3. Upload a webextension

## expected behavior:
Unlisted webextensions are not automatically signed.

## observed behavior:
Unlisted webextensions are automatically signed.

## additional notes:
On stage, we don't accept webextension submissions yet. That makes this issue a non-blocker.

## screenshot
https://www.dropbox.com/s/2rkup8i33d9b6b2/Screenshot%202015-12-02%2015.18.41.png?dl=0

**Comment by magopian** [comment]
Thanks for filing this issue, but according to https://github.com/mozilla/olympia/issues/942#issuecomment-161079311 we do want to auto-sign unlisted WebExtensions after all.
