### ISSUE TITLE
Display issue in waiting time row in Editor tools

### ISSUE THREAD

**Issue by madalincm** [mozilla/olympia#1034]
Steps to reproduce: 
1. Open https://addons.allizom.org/en-US/editors/queue/nominated
2. Observe the waiting time row.

Expected results:
There are no display issues.

Actual results:
There is a small text displayed under the arrow.

Notes/Issues:
The issue can be reproduced in all the queues Pending updates, preliminary review etc.
Verified in FF42(Win7) Issue can be reproduced in addons.allizom.org and addons-dev.allizom.org
Screencast for this issue: http://screencast.com/t/oDKuAaK408X

**Comment by magopian** [comment]
Hi, thanks for filing, I saw that this morning and I've already fixed it in #1032.

**Comment by madalincm** [comment]
looks good now: http://screencast.com/t/IWcx9uMfro3V
Marking as verified fixed.
