### ISSUE TITLE
Unlisted-Sideloaded addons are not automatically signed on AMO-dev

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/olympia#1037]
Steps to reproduce:
1. Sign in to AMO-dev Developer Hub - https://addons-dev.allizom.org/en-US/developers/
2. Submit an unlisted-sideloaded (bundled) addon (i.e. 02.12.Addon)

Expected results:
The add-on is automatically signed. Add-on status is "fully reviewed".

Actual results:
The add-on is not automatically signed.

Notes/Issues:
The issue is also happening for webextensions.
Verified on FF42(Win 7). Issue is only reproducing on AMO-dev.
Please see the screenshot: 
![2015-12-03_1712](https://cloud.githubusercontent.com/assets/15685960/11564270/0a111b62-99e1-11e5-9cee-605ec2ccfbe9.png)

**Comment by magopian** [comment]
Fixed now, it was linked to a deployment issue on the dev server. Thanks!
