### ISSUE TITLE
It should not be possible to review files that are not pending review

### ISSUE THREAD

**Issue by wagnerand** [mozilla/olympia#1046]
Imagine the following scenario:

1. Reviewer A (wrongfully) rejects a version/file.
2. Reviewer B notices and just submits the review form again, this time approving the add-on.

What happens is that the file is marked as approved, but the signing process is not run. This has happened multiple times alone this week.

What we want to happen is to disallow the review if the file is in a non-pending state. So, either the `Submit` button should be disabled for approving/rejection action, or those actions shouldn't be even shown.

Caveats:
1) Be aware that there might be several files for a version, and they might have different review states, e.g. one is pending review, the other one is not.
2) There is one exception to the general rule. If the file status is `STATUS_LITE` and the add-on status is `STATUS_LITE_AND_NOMINATED` (that means, if a developer requested full review for their already preliminary reviewed version), it should of course be possible to submit a review.

Background info: The correct way to re-review a version/file is for an admin to put the file back to a pending-review state before submitting the corrected review.

**Comment by magopian** [comment]
So, after further investigation, it should not be possible to review files that are not pending review since #744 landed.

So while it would be much better to have some kind of feedback to the reviewer that his action didn't do anything if there was no pending files, I'm suspecting this issue is caused by something else, maybe some modification in the admin tools?

**Comment by magopian** [comment]
I'd like to follow-up on this one, can you confirm @wagnerand that this issue can be closed? I believe the issue was due to some manual modifications through the admin?

**Comment by wagnerand** [comment]
This was definitely not caused by some action in the admin tools. I suspect it is related to the move to AWS where some transactions just take longer and therefore reviewers were able to submit a review multiple times.
Closing for now, until we can reproduce.
