### ISSUE TITLE
Remove perf

### ISSUE THREAD

**Issue by andymckay** [mozilla/olympia#1058]
Performance testing of add-ons is no more. This is a telling comment:

```
# These are all the apps available for a file to be tested against:
ALL_APPS = ('firefox3.6', 'firefox6.0')
```

Lets remove `apps/devhub/perf.py` and everything related to it.

**Comment by magopian** [comment]
Seems it was (partially) removed in b46ab42 : it removed the code that was updating the `Addon.ts_slowness` field.
