### ISSUE TITLE
Sign a listed add-on before it is approved

### ISSUE THREAD

**Issue by kumar303** [mozilla/olympia#1066]
As requested by Honza in [bug 1230073](https://bugzilla.mozilla.org/show_bug.cgi?id=1230073):

> (In reply to Jan Honza Odvarko [:Honza] from comment #5)
> So, here is what I need:
> - have the add-on listed on AMO, so I can use AMO as distribution channel
> - distribute signed version of the add-on using my secondary channel, so
> users don't have to wait till the add-on passes the review.

I don't think this is currently possible. I guess the only way to currently do it would be to submit one unlisted add-on and one listed add-on but I can see how that would be annoying.

@jvillalobos Is this something anyone has considered supporting?

**Comment by jvillalobos** [comment]
Having separate channels for the same ID is something I would like us to support, but it's not possible at the moment. I commented this to @andymckay when we met back in Toronto, but it's too complex to do before the rewrite (if we go that way).

At the moment there are two options:
# Use different IDs.
# Use the beta channel of the add-on. If a listed add-on is fully reviewed, the developer can enable the beta channel and submit beta versions, which are signed without review. Those versions could be distributed outside of AMO without any problems.

**Comment by andymckay** [comment]
We've got two workarounds for this scenario, but at this point until a rewrite happens, this isn't going to change.
