### ISSUE TITLE
JWT compares client clock with server clock - design error

### ISSUE THREAD

**Issue by benbucksch** [mozilla/olympia#1072]
xref issue #1071 is the hot fix
This bug here tries to get to the root of the problem.

------
Story:

We wrote a script to upload our builds to AMO as part of our build process.

The code was working for Neil, who wrote the script, but I just got "Invalid authentication credentials".

We were debugging it for hours and hours, suspecting shell argument passing and parsing, OS differences and what not. We compared credentials and confirmed they are identical. Still, the result was different.
During debugging, once, by coincidence, it worked. At a time when it should be expired.

What was the reason? My clock on my computer was fast.

I was screaming. Client server protocols must NEVER EVER compare client clocks with server clocks, because clocks are very often off. Even if it was originally set exactly right by the second, clocks always have a drift in one way or another. If you have 5 million users, you will surely have 500000 whose clocks are off by 1 minute, and 50000 users whose clocks are off more than that.
In my case, my clock was 95 seconds fast. That's not uncommon. I don't run ntpdate regularly, because ntp regularly has security problems, too.

-------

This is a fatal misdesign of the protocol. You simply cannot compare client clock with server clocks. That something that engineers generally know from experience. Often hard lessons, like mine above. Sometimes worse lessons, when 5 million people were hit by this problem.

If this problem is inherent in the JWT protocol, then it was mis-designed and you can't use JWT, simple as that.

Please note that an RFC doesn't make it a standard. It's merely a proposal. RFC means "Request for comment". My experience shows that JWT is not suited for deployment, at all. Please replace it (please read on, alternative below).

-----------

Theoretical concerns aside, JWT is completely unnecessary here at AMO. For the AMO website, I have one single AMO account password, and because we're a team working on that extension, I need to share this password with several people in the organization. That's where your security weakness is.

Separating the scripts from the main password, what you tried to do here in JWT, was a wise move. Putting the main AMO password in build scripts would be dead stupid. However, instead of letting me generate JWT credentials on AMO, you could simply let me generate a second password which is specifically for the upload API, and works only there. Then let me send that using standard HTTP Auth when I upload builds.

Security-wise, that's equivalent. Whether I store a JWT user and JWT secret or a username and password is strictly same, it's just a different term for the same thing. Given that JWT can generate tokens from the user/secret at any time, it doesn't add any security. All JWT protects is the wire data, so it helps only when you mistrust HTTPS - but then you have the same trouble with my main AMO login in the browser, so it didn't help.

The advantage of using standard HTTP Auth is that it's a standard (and *actual* standard) and implemented in almost all HTTP clients. I wouldn't need funny python modules and import them into my build system. Security-wise, it would be the same.

**Comment by wagnerand** [comment]
> This is a fatal misdesign of the protocol. You simply cannot compare client clock with server clocks.
To be fair, most multi-factor authentication systems rely on TOTP (time-based!)

> I have one single AMO account password, and because we're a team working on that extension, I need to share this password with several people in the organization.
You can add multiple owners/developers (accounts) to your add-on. I am fairly sure this would enable you to have multiple users be able to use the signing API for your add-on.

**Comment by benbucksch** [comment]
> You can add multiple owners/developers (accounts) to your add-on

I didn't know, thank you, we'll do that.

> most multi-factor authentication systems rely on TOTP (time-based!)

From what I understand, OAuth for example generates a token on the server, and that token includes the server time as expiry, so the server compares server to server time. JWT is the first I ever see where the client generates the token with expiry itself.

I debugged this for hours during 2 days, and finally it was the clock. I would never have thought the clock would influence my code.

This made me remember the "Bastard Operator From Hell #4" story that I read a decades ago.
<http://bofh.ntk.net/BOFH/0000/bastard04.php>
> "Now I'm in a *REALLY* good mood. I think I just might write that script to make saving impossible on rogue at random times like I've been thinking about" ...
> "the earth's magnetic field is particularly strong today."

This bug here was the closest to this BOFH story I ever got in my engineering life. :-) The clock drift...

FWIW, I checked the spec, the "iat" is supposed to be the "time of issue", so a clock drifting in the fast direction is bound to cause errors.

**Comment by kumar303** [comment]
> You simply cannot compare client clock with server clocks.

Sure you can. The client can just sync their clock with [NTP](http://ntp.org/) as stated in Olympia's API docs.

JWTs (and many other signature based authentication) will need to rely on timestamps to prevent replay attacks. I'm closing this because NTP syncing should be sufficient to deal with this.

**Comment by benbucksch** [comment]
> The client can just sync their clock with NTP as stated in Olympia's API docs.

No, it cannot. Only root can change the clock. The JWT client cannot do that.
You cannot assume that all people have perfect clocks. That's a ridiculous assumption.

**Comment by kumar303** [comment]
I think it's reasonable to expect that a client who calls our API has a clock that is in sync with the world. Pretty much all APIs rely on a synchronized client clock. Oauth 1.0, for example, requires your clock to be in sync. A quick search shows that Twitter's API [requires the client's clock to be in sync](https://twittercommunity.com/t/troubleshooting-oauth-1-0a/231), just as an example.

In the story of your original bug report you mention that the problem was your computer. What is preventing you from syncing your clock using NTP or something similar? (time.apple.com on Mac, etc.)

> Theoretical concerns aside, JWT is completely unnecessary here at AMO. 

JWTs provide enhanced security for API access because instead of passing a token that might be intercepted and re-used by an attacker (like a password or a session cookie), you only pass a signature, which cannot be re-used. Oauth 1.0 works just the same and is the authentication mechanism for many APIs out there. JWT is a little simpler than Oauth.

> For the AMO website, I have one single AMO account password, and because we're a team working on that extension, I need to share this password with several people in the organization. That's where your security weakness is.

You shouldn't have to share your API credentials with anyone. AMO supports team members for add-ons (go to *Manage Authors and License*). For each assigned team member, their personal API credentials should allow them to push updates to the shared add-on. Please open a bug if that isn't working.

**Comment by benbucksch** [comment]
I am just implementing OAuth in a project, and OAuth 2.0 definitely uses server clock vs. server clock, if the token considers clock at all. There isn't even any way to consider the client clock in the protocol.

I never claimed that there are no APIs that do this. I specifically said there's no *widespread* protocol, meaning HTTP, IMAP, SMTP or similar, that does this.

> In the story of your original bug report you mention that the problem was your computer. What is preventing you from syncing your clock using NTP or something similar?

My problem is solved. But it took me 2 work days (!) to find the problem. The purpose of the bug report is that I want to prevent that somebody else falls in the same trap and having to suffer as I did.

**Comment by kumar303** [comment]
Oauth 2.0 can still [suffer from client clock skew](https://rnd.feide.no/2012/04/19/best-practice-for-dealing-with-oauth-2-0-token-expiration-at-the-consumer/). Maybe we're talking about different things? When I say "client clock skew" I mean the clock of the server that the client is connecting to our API from.

> there's no widespread standard protocol...that does this

SSL/TLS certs rely on client clocks for [certificate validation](http://security.stackexchange.com/questions/72866/what-role-does-clock-synchronization-play-in-ssl-communcation) (same concept, same problem).

>  If you don't trust SSL with a password

It's a lot harder to trust SSL/TLS when the client is not a web browser. For example, a lot of standard Python libs will make requests without checking certs by default. This is generally why APIs typically don't let you connect simply with a username and password.

Using JWTs really isn't about a mistrust of SSL though. After some kind of authentication (even if it were presenting a username + password) we would need a way to maintain a token for the session. If we use a signature approach (which requires sync'd clocks) then we don't have to maintain a local database of valid tokens -- we can just check the signature.

> It took me 2 days (!) to find the problem.

Yeah, that sucks. I think we can return a more informative authentication failure message.

I think another problem here is that our clock skew allowance is too short, which we can fix.

**Comment by benbucksch** [comment]
> SSL/TLS certs rely on client clocks for certificate validation (same concept, same problem).

OK, but there, we're in the year or month range, at most days.

My clock was 90 seconds fast. When I was in vacation and came back, my computer's clock was 20 minutes fast. That's fine for SSL purposes.

The problem here is that you're enforcing the client time on a second precision. I am not allowed to put iat even 1 seconds in the future, or your server will bail, so a clock being only 2 seconds will make things fail.

**Comment by wagnerand** [comment]
>> most multi-factor authentication systems rely on TOTP (time-based!)
> Not on the client clock, no.

Google's TOTP does that, for example. I have a private server which uses that mechanism and its clock was off by a minute or so. It did not any of the keys generated by the Google Authenticator app.

**Comment by kumar303** [comment]
> The problem here is that you're enforcing the client time on a second precision

It allows for 5 seconds of drift currently but I filed https://github.com/mozilla/olympia/issues/1498 to give it more leeway.

**Comment by kumar303** [comment]
Until the leeway is added, the error message should be more obvious now (see https://github.com/mozilla/olympia/pull/1514)

**Comment by benbucksch** [comment]
I just got another security update for ntpdate. The security bugs in ntp just don't stop. Take a look at this, how many in a year:
http://changelogs.ubuntu.com/changelogs/pool/main/n/ntp/ntp_4.2.6.p3+dfsg-1ubuntu3.8/changelog
This is why I don't do ntp syncs. They are a security risk. Sad but true.

**Comment by kumar303** [comment]
Oh, huh, good point. I hadn't looked into this. Actually, I see that Hanno in our services group [recommends](https://blog.hboeck.de/archives/863-Dont-update-NTP-stop-using-it.html) to use [tlsdate](http://linux-audit.com/tlsdate-the-secure-alternative-for-ntpd-ntpdate-and-rdate/).

**Comment by benbucksch** [comment]
Interesting, thanks.

**Comment by kumar303** [comment]
Thanks for this tip. I adjusted our exception message to no longer recommend NTP :) https://github.com/mozilla/olympia/pull/1617
