### ISSUE TITLE
Redirect all login links to fxa

### ISSUE THREAD

**Issue by krupa** [mozilla/olympia#1079]
## steps to reproduce:
0. User is not logged in.
1. Load https://addons-dev.allizom.org/en-US/firefox/addon/quickwiki/?src=hp-dl-featured
2. Click on Add to Collection -> log in to your account

## expected behavior:
FxA flow loads

## actual behavior:
https://addons-dev.allizom.org/en-US/firefox/users/login?to=%2Fen-US%2Ffirefox%2Faddon%2Fquickwiki%2F%3Fsrc%3Dhp-dl-featured loads

**Comment by krupa** [comment]
Same thing applies for Dev hub: https://addons-dev.allizom.org/en-US/firefox/users/login?to=/en-US/developers/addon/submit/1

Also, write a review link: https://addons-dev.allizom.org/en-US/firefox/users/login?to=/en-US/firefox/addon/flagfox/reviews/add

**Comment by ValentinaPC** [comment]
In the same case are the following:
1. Submit theme: https://addons-dev.allizom.org/en-US/firefox/users/login?to=/en-US/developers/theme/submit 
2. Add-on validator: https://addons-dev.allizom.org/en-US/firefox/users/login?to=/en-US/developers/addon/validate
3. Submit new collection: https://addons-dev.allizom.org/en-US/firefox/users/login?to=/en-US/firefox/collections/add
4. Collections I' ve made/I' m Following/My Favorite Add-ons: 
-https://addons-dev.allizom.org/en-US/firefox/users/login?to=/en-US/firefox/collections/mine/
-https://addons-dev.allizom.org/en-US/firefox/users/login?to=/en-US/firefox/collections/following/
-https://addons-dev.allizom.org/en-US/firefox/users/login?to=/en-US/firefox/collections/mine/favorites

**Comment by mstriemer** [comment]
Since the migration flow now starts on the old login page these should all be fixed now.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev using FF43(Win 7).
Postfix screencast: http://screencast.com/t/CyKSmQhGp
Closing bug.
