### ISSUE TITLE
Clicking on Contents for a webextension loads a 404

### ISSUE THREAD

**Issue by krupa** [mozilla/olympia#1086]
## steps to reproduce
1. Submit a web extension to AMO
2. Go to Editor tools and navigate to the reviewer details page for that add-on
3. Click on the 'Contents' link for that add-on

## observed behavior
https://addons-dev.allizom.org/en-US/firefox/files/browse/247966/ is a 404
https://addons-dev.allizom.org/en-US/editors/review/sort-tabs-by-url11 is a 404

## Notes:
Link for older extensions work fine.

**Comment by magopian** [comment]
Issue was due to the fact that when displaying the file viewer, it tries to display the `install.rdf` file by default, which isn't there for a WebExtension. See #1115.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF43(Win 7).
Postfix screencast: http://screencast.com/t/gt6e9Ba5NHD
