### ISSUE TITLE
Downloaded file hash did not match provided hash

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/olympia#1089]
This is a clone of https://github.com/mozilla/addons/issues/12

rkent:

In trying to download my extension, the following error occurs (tried in both Windows and OSX and both show this):

1450131310950 addons.xpi WARN Download of https://addons.mozilla.org/thunderbird/downloads/file/317904/exquilla_for_microsoft_exchange-38.0.1159-tb-windows.xpi?src=api failed: Downloaded file hash (e4d37fc12bd11cde81584c1d5de76cca9a8bd5dac3c065490040bc6812b50cd5) did not match provided hash (d1bc6f3cf1777cf860398f13ceb01c8fe17e54344b39212a5232b9d6608a2e94)

The addon was recently update on Dec 4 automatically with this message:

"Your add-on, ExQuilla for Microsoft Exchange, has been automatically fixed for future versions of
Firefox (see https://blog.mozilla.org/addons/2015/10/14/breaking-changes-let-const-firefox-nightly-44/). The fixing process involved repackaging the add-on files and adding the string
'.1-let-fixed' to their versions numbers."

It is likely that the hash mismatch occurred during that automatic update.

Today I observed a similar issue in Firefox when in opened the add-ons manager, searched for 'Chrome List' and tried to install the add-on. The download worked, but an issue occurred later, so it's likely that's is also a hash issue. Wasn't able to reproduce the issue afterwards.

**Comment by Archaeopteryx** [comment]
Another affect extension: https://addons.mozilla.org/en-US/firefox/addon/mediathread/

**Comment by nikolas** [comment]
The mediathread problem is being tracked in this ticket: #1111

**Comment by andymckay** [comment]
Seems familiar to the Android bug.

**Comment by andymckay** [comment]
Tracker: #1244, we are hoping this will be fixed with the changes to the transaction handling.
