### ISSUE TITLE
Contents/Compare links from WebExtension review page return a 404 page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/olympia#1095]
Steps to reproduce:
1. Sign into AMO-dev with an admin account: https://addons-dev.allizom.org/en-US/
2. Submit a WebExtension (i.e. Webext-test-1)
3. Load review page for that extension (i.e. https://addons-dev.allizom.org/en-US/editors/review/webext-test-1)
4. Click on a "Content" link

Expected results:
Extension content page is loaded. There are no issues.

Actual results:
A 404 page is loaded.

Notes/Issues:
Issue is not reproduced for simple-extensions.
Verified on FF43(Win 7). Issue is reproducing on AMO-dev.
Screencast for this issue: http://screencast.com/t/fBN9xGlj

**Comment by ValentinaPC** [comment]
Krupa logged this issue before I did. :) ( https://github.com/mozilla/olympia/issues/1086 )

**Comment by magopian** [comment]
Closing as duplicate.
