### ISSUE TITLE
Windows .XPI version is corrupted

### ISSUE THREAD

**Issue by Soffid** [mozilla/olympia#1101]
I've just uploaded a new addon (Soffid ESSO Firefox addon). This addon runs on Windows and Linux, and two .XPI files has been generated and signed by AMO. 

But when I try to install Windows .XPI version, Firefox complains about it, and say it is corrupt. Suprisingly, if I try to install Linux .XPI version everything  works fine.

**Comment by andymckay** [comment]
Corrupt is a pretty generic message that can occur in multiple situations. Please check the Browser Console (not the Web Console) for any messages on installing the Add-on to see what the message is. Also, please tell us what version of Firefox this is.

**Comment by wagnerand** [comment]
Note: Firefox throws this error for signature related errors as well: http://mxr.mozilla.org/comm-release/source/mozilla/toolkit/mozapps/extensions/internal/XPIProvider.jsm#5034

**Comment by Soffid** [comment]
I've tried to download again the XPI file from OMA and now it's working
fine.

Unfortunately I didn't keep a copy of the corrupt XPI file. May be it was a
network corruption or OMA server problem.

My apologies for any inconvenience. Thank you very much.


Gabriel Buades
*Soffid* CEO
✉ gbuades@soffid.com
☎ +34-871962912
✆ +34-639660155
Skype: gbuadesr


*Please consider the environment before printing this email*

This email and any attachments are property of Soffid IAM SL. It may
contain confidential or privileged information, so it is absolutely
forbidden to copy, reproduce, publish and distribute their contents and the
use of this material for any other purpose that is not strictly authorized, as
stated at Intellectual Property and Data Protection laws.

2015-12-16 23:27 GMT+01:00 Andy McKay <notifications@github.com>:
