### ISSUE TITLE
Duplicate add-on ID for mediasetplayer

### ISSUE THREAD

**Issue by kumar303** [mozilla/olympia#1112]
We got a report about a user who keeps getting this error : 
````
jpm sign --api-key=user:10822560:122 --api-secret=... --xpi=mediasetplayer-1.2.13396-mingw-w32.xpi
JPM [info] Signing XPI: mediasetplayer-1.2.13396-mingw-w32.xpi
JPM [error] Server response: Duplicate add-on ID found. ( status: 400 )
JPM [info] FAIL
````
They have uploaded a couple different versions and it appears some have differing platform files.

**Comment by buddhistsforbernie** [comment]
I am getting this same error with all my addons, after deleting old versions from the site:

DPRMyanmar@noah.yuttadhammo
DPRThai@noah.yuttadhammo
sanskrit@noah.yuttadhammo
digitalpalireader@noah.yuttadhammo

Error with DPRMyanmar.xpi
100% complete · 22.58 MB of 22.58 MB
Your add-on failed validation with 1 error.

    Duplicate add-on ID found.

**Comment by wagnerand** [comment]
> I am getting this same error with all my addons, after deleting old versions from the site:

This isssue is about something else. Please send an email to amo-admins AT mozilla DOT org.

**Comment by andymckay** [comment]
Closing based on request to email amo-admins.

**Comment by wagnerand** [comment]
@andymckay This is still a valid issue, which needs to be investigated. Only https://github.com/mozilla/olympia/issues/1112#issuecomment-165978900 was misplaced.

**Comment by bgiaccio** [comment]
I'm also getting the Duplicate add-on ID message, yet the same xpi file will upload just fine via the Browser interface.

**Comment by kumar303** [comment]
hmm, if jpm is detecting the version wrong then this might be the same bug as https://github.com/mozilla-jetpack/jpm/issues/450 . Could you attach a copy of the XPI file you saw the 'duplicate ID' message for?

**Comment by kmurph92** [comment]
Same issue for me here. I submitted an XPI, then deleted the submission, then tried to submit the same XPI and it resulted in "Duplicate add-on ID found" during validation.

**Comment by wagnerand** [comment]
> Same issue for me here. I submitted an XPI, then deleted the submission,
> then tried to submit the same XPI and it resulted in "Duplicate add-on ID
> found" during validation.
>
That is not what this issue is about. Deleting your ID results in it being
added to a submission block list to avoid hostile takeover. Please send an
email to amo-admins AT mozilla DOT org and mention your add-on ID.

**Comment by bgiaccio** [comment]
I may have found the root cause (or at least my root cause).  My add-on didn't have a package.json file, without it uploading via the Web Page works just fine but without it you get the Duplicate-ID problem.  Add the file (with appropriate values) and it works just fine.

**Comment by warrendodsworth** [comment]
Simple question, where do I find the addon ID to submit it to their email. 
Bug report  - I used submit for signing only signing beta - then I couldn't edit the addon to listed. So I deleted it and am trying without that option checked, as I'd like to list the addon now. 

But this is preventing me from doing it.

**Comment by jvillalobos** [comment]
The add-on ID is in the install.rdf file.

**Comment by kumar303** [comment]
This was fixed in https://github.com/mozilla-jetpack/jpm/issues/465
