### ISSUE TITLE
add-on valdation failed with 1 error, but in the validation report is no error or warning

### ISSUE THREAD

**Issue by juhulian** [mozilla/olympia#1118]
i have tried to upload a little addon to the amo, but the validation failed with 1 error. so looked into the full validation report, but there was no error or warning...
![submit](https://cloud.githubusercontent.com/assets/5305965/11935680/7678b144-a809-11e5-92c6-ef66c499737d.JPG)
![validation_report](https://cloud.githubusercontent.com/assets/5305965/11935679/76786bf8-a809-11e5-9564-a6640d58b1ee.JPG)

**Comment by wagnerand** [comment]
The first screenshot says:
```
WebExtensions aren't allowed yet
```

**Comment by juhulian** [comment]
oh, i see. Thx!
you cann't run frefox with a unsiged webextesion, but you also cann't sign a webextention...

**Comment by andymckay-limited-access** [comment]
You can turn off signing or use beta or nightly to play around with
WebExtensions.

We are just doing final QA on using WebExtensions on AMO to make sure it
all works as expected.
