### ISSUE TITLE
Possible retry loop in validator celery tasks

### ISSUE THREAD

**Issue by kumar303** [mozilla/olympia#1126]
from @jasonthomas , to me, in an email:

Attached are 4 messages in the queues used by exchange celeryresults.

Also attached is a strace output from `devhub.tasks.handle_upload_validation_result` tasks that seem to continuously retry on a 1 second interval. 

[strace.celery.txt](https://github.com/mozilla/olympia/files/69197/strace.celery.txt)
[celery1.txt](https://github.com/mozilla/olympia/files/69198/celery1.txt)
[celery2.txt](https://github.com/mozilla/olympia/files/69199/celery2.txt)
[celery3.txt](https://github.com/mozilla/olympia/files/69200/celery3.txt)
[celery4.txt](https://github.com/mozilla/olympia/files/69201/celery4.txt)

**Comment by andymckay** [comment]
Tracker #1244, because I think this is related to chords, which @kumar303 said he'd dig into a bit.

**Comment by andymckay** [comment]
We don't think this is a problem.
