### ISSUE TITLE
XPI file returned from "jpm sign" is not signed

### ISSUE THREAD

**Issue by ct-parker** [mozilla/olympia#1138]
I am attempting to sign a self-hosted XPI file with `jpm sign`, and I have the round-trip completing, but the returned XPI file is not signed.

The add-on passes automatic validation and the "Downloading signed files" and "SUCCESS" messages indicate that the "guide-2015.1222.1649.xpi" file should be signed, but it is byte-for-byte identical to the original, unsigned XPI that I submitted.

I'm not certain if this a bug, or if my expectations are wrong. The complete jpm output are pasted below.

The XPI is an older XUL-based overlay that was initially written in 2008 but has been working until Firefox 43.0 due to the signing requirement.

    [zip] Building zip: C:\workspace\guide-firefox\build\guide-firefox-2015.1222.1649.xpi
           JPM [info] verbose set
           JPM [info] Signing XPI: C:\workspace\guide-firefox\build\guide-firefox-2015.1222.1649.xpi
           JPM [debug] [API] -> { url: 'https://addons.mozilla.org/api/v3/addons/%7B05e23afc-0001-0040-b97d-6096003164ae%7D/versions/2015.1222.1649/',
             formData: 
              { upload: 
                 { _readableState: [Object],
                   readable: true,
                   domain: null,
                   _events: [Object],
                   _maxListeners: undefined,
                   path: 'C:\\\workspace\\guide-firefox\\build\\guide-firefox-2015.1222.1649.xpi',
                   fd: null,
                   flags: 'r',
                   mode: 438,
                   start: undefined,
                   end: undefined,
                   autoClose: true,
                   pos: undefined } },
             headers: { Authorization: '<REDACTED>', Accept: 'application/json' } }
           JPM [debug] [API] <- { headers: 
              { allow: 'GET, PUT, HEAD, OPTIONS',
                'content-type': 'application/json',
                date: 'Tue, 22 Dec 2015 21:49:15 GMT',
                server: 'nginx',
                'set-cookie': '<REDACTED>',
                'strict-transport-security': 'max-age=31536000',
                vary: 'Accept, X-Mobile, User-Agent',
                'x-backend-server': 'ip-172-31-12-253',
                'x-frame-options': 'DENY',
                'content-length': '500',
                connection: 'Close' },
             response: 
              { active: false,
                automated_signing: true,
                url: 'https://addons.mozilla.org/api/v3/addons/%7B05e23afc-0001-0040-b97d-6096003164ae%7D/versions/2015.1222.1649/uploads/eb614b0d79eb4610b08c83c93d912f26/',
                files: [],
                passed_review: false,
                pk: 'eb614b0d79eb4610b08c83c93d912f26',
                processed: false,
                reviewed: false,
                valid: false,
                validation_results: null,
                validation_url: 'https://addons.mozilla.org/en-US/developers/upload/eb614b0d79eb4610b08c83c93d912f26',
                version: '2015.1222.1649' } }
           JPM [debug] [API] -> { url: 'https://addons.mozilla.org/api/v3/addons/%7B05e23afc-0001-0040-b97d-6096003164ae%7D/versions/2015.1222.1649/uploads/eb614b0d79eb4610b08c83c93d912f26/',
             headers: { Authorization: '<REDACTED>', Accept: 'application/json' } }
           Validating add-on [          .                                                 ]Validating add-on [          .                                             .   ]Validating add-on [          .                      .                      .   ]Validating add-on [          .                      .                .     .   ]Validating add-on [          .                .     .                .     .   ]Validating add-on [          .                .     .      .         .     .   ]JPM [debug] [API] <- { headers:    { allow: 'GET, PUT, HEAD, OPTIONS',
                'content-type': 'application/json',
                date: 'Tue, 22 Dec 2015 21:49:16 GMT',
                server: 'nginx',
                'strict-transport-security': 'max-age=31536000',
                vary: 'Accept, X-Mobile, User-Agent',
                'x-backend-server': 'ip-172-31-12-253',
                'x-frame-options': 'DENY',
                'content-length': '500',
                connection: 'Close' },
             response: 
              { active: false,
                automated_signing: true,
                url: 'https://addons.mozilla.org/api/v3/addons/%7B05e23afc-0001-0040-b97d-6096003164ae%7D/versions/2015.1222.1649/uploads/eb614b0d79eb4610b08c83c93d912f26/',
                files: [],
                passed_review: false,
                pk: 'eb614b0d79eb4610b08c83c93d912f26',
                processed: false,
                reviewed: false,
                valid: false,
                validation_results: null,
                validation_url: 'https://addons.mozilla.org/en-US/developers/upload/eb614b0d79eb4610b08c83c93d912f26',
                version: '2015.1222.1649' } }
           Validating add-on [          .                .  .  .      .         .     .   ]Validating add-on [          .                .  .  .      .         .   . .   ]Validating add-on [          .                .  .  . .    .         .   . .   ]Validating add-on [          .                .  .  . .    .         .   ...   ]Validating add-on [    .     .                .  .  . .    .         .   ...   ]Validating add-on [    .     .             .  .  .  . .    .         .   ...   ]Validating add-on [    ..    .             .  .  .  . .    .         .   ...   ]Validating add-on [    ..    .             .  .  .  . .    .     .   .   ...   ]Validating add-on [    ..    .             .  .  .  . .    .    ..   .   ...   ]JPM [debug] [API] -> { url: 'https://addons.mozilla.org/api/v3/addons/%7B05e23afc-0001-0040-b97d-6096003164ae%7D/versions/2015.1222.1649/uploads/eb614b0d79eb4610b08c83c93d912f26/',  headers: { Authorization: '<REDACTED>', Accept: 'application/json' } }
           Validating add-on [    ..    .             .  .  .  . .    .    ..   .   ...  .]Validating add-on [    ..    .             . ..  .  . .    .    ..   .   ...  .]Validating add-on [    ..    .             . ..  .  . .    .    ..   .   ... ..]Validating add-on [    .. .  .             . ..  .  . .    .    ..   .   ... ..]Validating add-on [    .. .  .  .          . ..  .  . .    .    ..   .   ... ..]Validating add-on [    .. .  .  .          . .. ..  . .    .    ..   .   ... ..]JPM [debug] [API] <- { headers:    { allow: 'GET, PUT, HEAD, OPTIONS',
                'content-type': 'application/json',
                date: 'Tue, 22 Dec 2015 21:49:17 GMT',
                server: 'nginx',
                'strict-transport-security': 'max-age=31536000',
                vary: 'Accept, X-Mobile, User-Agent',
                'x-backend-server': 'ip-172-31-12-254',
                'x-frame-options': 'DENY',
                'transfer-encoding': 'chunked',
                connection: 'Close' },
             response: 
              { active: false,
                automated_signing: true,
                url: 'https://addons.mozilla.org/api/v3/addons/%7B05e23afc-0001-0040-b97d-6096003164ae%7D/versions/2015.1222.1649/uploads/eb614b0d79eb4610b08c83c93d912f26/',
                files: [],
                passed_review: false,
                pk: 'eb614b0d79eb4610b08c83c93d912f26',
                processed: true,
                reviewed: false,
                valid: true,
                validation_results: 
                 { errors: 0,
                   success: false,
                   warnings: 16,
                   compatibility_summary: [Object],
                   passed_auto_validation: true,
                   ending_tier: 5,
                   messages: [Object],
                   detected_type: 'extension',
                   signing_summary: [Object],
                   notices: 3,
                   message_tree: [Object],
                   metadata: [Object] },
                validation_url: 'https://addons.mozilla.org/en-US/developers/upload/eb614b0d79eb4610b08c83c93d912f26',
                version: '2015.1222.1649' } }
           Validating add-on [    .. .  .  ..         . .. ..  . .    .    ..   .   ... ..]Validating add-on [ .  .. .  .  ..         . .. ..  . .    .    ..   .   ... ..]Validating add-on [ .  .. .  .  ..         . .. ..  . .    .    ..  ..   ... ..]Validating add-on [ .  .. .  .  ..         .... ..  . .    .    ..  ..   ... ..]Validating add-on [ .  .. .  .  ..         .... ..  . .    .   ...  ..   ... ..]Validating add-on [ .  .. . ..  ..         .... ..  . .    .   ...  ..   ... ..]Validating add-on [ .. .. . ..  ..         .... ..  . .    .   ...  ..   ... ..]Validating add-on [ .. .. . ..  ..         .... ... . .    .   ...  ..   ... ..]Validating add-on [ .. .. . ..  ..         .... ... . . .  .   ...  ..   ... ..]JPM [debug] [API] -> { url: 'https://addons.mozilla.org/api/v3/addons/%7B05e23afc-0001-0040-b97d-6096003164ae%7D/versions/2015.1222.1649/uploads/eb614b0d79eb4610b08c83c93d912f26/',  headers: { Authorization: '<REDACTED>', Accept: 'application/json' } }
           Validating add-on [ .. .. . ..  ..         .... ... . ...  .   ...  ..   ... ..]Validating add-on [ .. .. . ..  ..         .... ... . .... .   ...  ..   ... ..]Validating add-on [ .. .. . ..  ..         .... ... . .... . . ...  ..   ... ..]Validating add-on [ .. .. . ..  ..         .... ... . ...... . ...  ..   ... ..]Validating add-on [ .. .. . ..  ..  .      .... ... . ...... . ...  ..   ... ..]JPM [debug] [API] <- { headers:    { allow: 'GET, PUT, HEAD, OPTIONS',
                'content-type': 'application/json',
                date: 'Tue, 22 Dec 2015 21:49:19 GMT',
                server: 'nginx',
                'strict-transport-security': 'max-age=31536000',
                vary: 'Accept, X-Mobile, User-Agent',
                'x-backend-server': 'ip-172-31-28-100',
                'x-frame-options': 'DENY',
                'transfer-encoding': 'chunked',
                connection: 'Close' },
             response: 
              { active: true,
                automated_signing: true,
                url: 'https://addons.mozilla.org/api/v3/addons/%7B05e23afc-0001-0040-b97d-6096003164ae%7D/versions/2015.1222.1649/uploads/eb614b0d79eb4610b08c83c93d912f26/',
                files: [ [Object] ],
                passed_review: true,
                pk: 'eb614b0d79eb4610b08c83c93d912f26',
                processed: true,
                reviewed: true,
                valid: true,
                validation_results: 
                 { errors: 0,
                   success: false,
                   warnings: 16,
                   compatibility_summary: [Object],
                   passed_auto_validation: true,
                   ending_tier: 5,
                   messages: [Object],
                   detected_type: 'extension',
                   signing_summary: [Object],
                   notices: 3,
                   message_tree: [Object],
                   metadata: [Object] },
                validation_url: 'https://addons.mozilla.org/en-US/developers/upload/eb614b0d79eb4610b08c83c93d912f26',
                version: '2015.1222.1649' } }
           Validating add-on [............................................................]JPM [info] Validation results: https://addons.mozilla.org/en-US/developers/upload/eb614b0d79eb4610b08c83c93d912f26
           Downloading signed files: ...Downloading signed files:   1% Downloading signed files:   2% Downloading signed files:   3% Downloading signed files:   5% Downloading signed files:   6% Downloading signed files:   8% Downloading signed files:   9% Downloading signed files:  10% Downloading signed files:  12% Downloading signed files:  12% Downloading signed files:  14% Downloading signed files:  15% Downloading signed files:  17% Downloading signed files:  18% Downloading signed files:  19% Downloading signed files:  21% Downloading signed files:  22% Downloading signed files:  24% Downloading signed files:  25% Downloading signed files:  26% Downloading signed files:  28% Downloading signed files:  28% Downloading signed files:  30% Downloading signed files:  31% Downloading signed files:  32% Downloading signed files:  34% Downloading signed files:  35% Downloading signed files:  36% Downloading signed files:  38% Downloading signed files:  39% Downloading signed files:  41% Downloading signed files:  42% Downloading signed files:  43% Downloading signed files:  45% Downloading signed files:  46% Downloading signed files:  47% Downloading signed files:  48% Downloading signed files:  49% Downloading signed files:  51% Downloading signed files:  51% Downloading signed files:  53% Downloading signed files:  54% Downloading signed files:  55% Downloading signed files:  57% Downloading signed files:  58% Downloading signed files:  59% Downloading signed files:  61% Downloading signed files:  62% Downloading signed files:  63% Downloading signed files:  65% Downloading signed files:  66% Downloading signed files:  68% Downloading signed files:  69% Downloading signed files:  71% Downloading signed files:  72% Downloading signed files:  73% Downloading signed files:  74% Downloading signed files:  75% Downloading signed files:  77% Downloading signed files:  78% Downloading signed files:  79% Downloading signed files:  81% Downloading signed files:  82% Downloading signed files:  84% Downloading signed files:  85% Downloading signed files:  87% Downloading signed files:  88% Downloading signed files:  89% Downloading signed files:  91% Downloading signed files:  92% Downloading signed files:  94% Downloading signed files:  94% Downloading signed files:  96% Downloading signed files:  97% Downloading signed files:  99% Downloading signed files: 100% JPM [info] Downloaded:
           JPM [info]     .\guide-2015.1222.1649.xpi
           JPM [info] SUCCESS

**Comment by andymckay-limited-access** [comment]
Is your add-on correctly identifying that it is for Firefox for Desktop?

**Comment by ct-parker** [comment]
I believe you zeroed in on the problem. I had this in my package.json:


    "engines":
    {
      "firefox": ">=38.0a1",
      "fennec": ">=38.0a1"
    },

but my (generated) install.rdf only had the following:

      <RDF:Description>
        <em:type>2</em:type>
        <em:minVersion>38.0</em:minVersion>
        <em:maxVersion>46.0</em:maxVersion>
      </RDF:Description>

At some point during the refactoring of my build process, I had lost my add-on's UUID and moved the `em:id` element (UUID) from `em:targetApplication/RDF:Description` into `RDF:RDF:Description`, so my add-on was trying to register as Firefox. Right element, wrong position/semantics.

I'm fairly confident this will solve the problem, but I'm getting timeouts from the jpm amo-client right now. As soon as I get a working build, I will close this issue.
