### ISSUE TITLE
Cannot install addons on -dev

### ISSUE THREAD

**Issue by vcarciu** [mozilla/olympia#1148]
Prerequisites:
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0

Steps to reproduce:
1.Go to https://addons-dev.allizom.org/
2.try to install any addon

Expected results:
Addons is successfully installed

Actual results:
Addons cannot be installed and we can see ReferenceError: hash is not defined error in console

Please see screencast for this bug : http://screencast.com/t/LmT02cPRtol

**Comment by diox** [comment]
I can reproduce locally, it started after 279a4aaac5e5c45cec9560c7a4f48485191eb4a7 according to git bisect.

**Comment by magopian** [comment]
Thanks a lot @diox for investigating and finding the root cause!
