### ISSUE TITLE
[Dev]Developer's photo overlap text in Contribute section

### ISSUE THREAD

**Issue by vcarciu** [mozilla/olympia#1149]
Prerequisites:
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0

Steps to reproduce:
1.Go to MP-dev and open any addon with contributions(ie .  https://addons-dev.allizom.org/ro/firefox/addon/adblock-plus/?src=hp-dl-mostpopular)
2.Observe contributions section

Expected results:
No UI issues

Actual results:
Developer's photo overlap text in Contribute section

Please see screencast for this bug : http://screencast.com/t/n78GHxnEVj

NOTES:
Not reproducible on Stage

**Comment by muffinresearch** [comment]
Fixed via #1237
