### ISSUE TITLE
Write load tests for devhub submission and editing

### ISSUE THREAD

**Issue by kumar303** [mozilla/olympia#1153]
I took a look at the access logs for a period when we're getting deadlocks (see https://github.com/mozilla/olympia/issues/1140) and I think it's worth writing a load test to see if we could reproduce it on stage. I was looking at access on 2015-12-23 (because of [deadlock spikes](https://sentry.prod.mozaws.net/operations/olympia-prod/group/151491/)) and we had 6522 add-on uploads (not simultaneous). This would be possible to recreate in a load test. It may not reveal the problem but it's worth a try.

**Comment by kumar303** [comment]
tests are being written here: https://github.com/mozilla/amo-loadtest

**Comment by andymckay** [comment]
Tracker #1244

**Comment by kumar303** [comment]
Load tests are up and running. Thanks @mstriemer !
