### ISSUE TITLE
Activate transactions for all non-consumer views

### ISSUE THREAD

**Issue by kumar303** [mozilla/olympia#1154]
I'd like to look at every exception in sentry that causes an integrity error and wrap the view in a transaction. These all look like data problems to me.

https://sentry.prod.mozaws.net/operations/olympia-prod/group/149540/

**Comment by diox** [comment]
You probably want https://docs.djangoproject.com/en/1.6/ref/settings/#std:setting-DATABASE-ATOMIC_REQUESTS to do it automatically. That's what we did in zamboni.

**Comment by kumar303** [comment]
@diox I would love to :) Unfortunately, AMO gets substantially more traffic than marketplace so I think we need to add transactions cautiously. We already know that we have performance issues (slow writes) that will be amplified if we turn on transactions everywhere because more views will be blocking when they did not block before. But I think we can make incremental progress.

**Comment by diox** [comment]
As discussed on Vidyo/IRC: `non_atomic_requests` decorator on the frontend views might help with that, assuming that they get most of the traffic (and that they don't do writes).

**Comment by kumar303** [comment]
Yeah! I think this is a better approach. I just graphed a count of the requests we get to [all of devhub](https://app.datadoghq.com/dash/87897/addons-apps) and it's tiny in comparison to the public pages. That makes it sound safe to turn on transactions everywhere except the public pages.

**Comment by andymckay** [comment]
You could also turn on transactions for all requests that are not anonymous (assuming that most of the traffic to public pages is not anonymous).

**Comment by andymckay** [comment]
Tracker #1244
