### ISSUE TITLE
Unlisted addon auto reviewed - but not signed

### ISSUE THREAD

**Issue by Noitidart** [mozilla/olympia#1158]
This addon here - https://addons.mozilla.org/de/developers/addon/geldstapel1/versions/1794900

Is unlisted, it go auto approved, however its not signed.

Also I tried installing it on Firefox 44 and Im getting a max version error, which I thought we don't do anymore for quite some time:

![](http://i.imgur.com/0Qa7BNr.png)

**Comment by magopian** [comment]
This addon doesn't set an "application" (or at least, not in a way we understand it), this is why it's not signed. You can see that in its devhub page, there's no supported application.
It shouldn't have been possible to submit it, was it "admin overriden"?

Closing this one for now, as it seems invalid.

**Comment by Noitidart** [comment]
Thanks @magopian  for that! We reached out to the dev.
