### ISSUE TITLE
Slow update query

### ISSUE THREAD

**Issue by andymckay** [mozilla/olympia#1162]
A first pass at the slow query log shows that a large number of slow queries are in:

    mysql-slow-query-downloads a "Query_time" -A 3 | grep UPDATE                                                                                              amo
    20151230.amo-olympia-db-master-prod-amoprod1.mysql-slowquery.log.12-48-UPDATE `file_uploads` SET `automated_signing` = 1, `addon_id` = ***** WHERE `file_uploads`.`uuid` = '*****';
  
Sometimes taking up to 2 minutes. I think this is here:

https://github.com/mozilla/olympia/blob/master/apps/devhub/views.py#L603

We are doing a insert then an update, we can probably make that more efficient.

**Comment by kumar303** [comment]
I think using the uuid as a primary key might be slowing down all other indexes. Because of clustering, each secondary index is ordered by the primary key but uuids introduce a couple problems. Info: https://www.percona.com/blog/2014/12/19/store-uuid-optimized-way/

**Comment by andymckay** [comment]
Just a note that this has occurred 36 times in the slow query log since 20151230.

**Comment by diox** [comment]
Note that *our* uuids are not stored in a optimal way at all : they are stored as `VARCHAR(32)` : https://github.com/andymckay/django-uuidfield/blob/master/uuidfield/fields.py#L80

I wonder if not using it as a PK but as a separate index would help (we would never expose the pk to the outside world, to prevent people from guessing each other validation results pages)

**Comment by EnTeQuAk** [comment]
36 times since end of last year isn't that much, is it?

If we'd store uuids as `BINARY` it will still hit write-performance for indices but I don't recall any performance problems for read queries.

Migrating to `BINARY` is tons of work though and the migration will probably require some kind of downtime to be safe.

**Comment by diox** [comment]
Yeah, I was not suggesting we move to `BINARY` yet. We should start by having a regular auto-incremented PK first.

**Comment by andymckay** [comment]
@mstriemer will clean up the code a little so it does less saves, @diox will change the table structure to have a primary key in #1182

**Comment by andymckay** [comment]
Tracker: #1244
