### ISSUE TITLE
[fx44]  Show compatibility error if an add-on uses __noSuchMethod__

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/olympia#1163]
As explained in [bug 683218](https://bugzilla.mozilla.org/show_bug.cgi?id=683218), the `__noSuchMethod__` JS property was removed. All instances must be flagged.

This is a compatibility error, so the add-on shouldn't be upgraded in this case. It should also appear as a warning in regular validations.

Message:

`__noSuchMethod__` has been removed. [Proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) should be used instead, if necessary. 

Affected add-on: https://addons.mozilla.org/addon/hatena-bookmark/

Release timing: Firefox 44 will be released on January 26th.

**Comment by EnTeQuAk** [comment]
PR: https://github.com/mozilla/amo-validator/pull/374
