### ISSUE TITLE
[fx44]  Show compatibility error if an add-on uses getAllStyleSheets

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/olympia#1164]
As explained in [bug 1141041](https://bugzilla.mozilla.org/show_bug.cgi?id=1141041), the `getAllStyleSheets` function was replaced with a new `getBrowserStyleSheets` function. All instances of `getAllStyleSheets` should be flagged.

This is a compatibility error, so the add-on shouldn't be upgraded in this case. It should also appear as a warning in regular validations.

Message:

The getAllStyleSheets function has been removed. You can use getBrowserStyleSheets instead. See [this bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1141041) for more information.

Affected add-on: https://addons.mozilla.org/addon/vimperator/

Release timing: Firefox 44 will be released on January 26th.

**Comment by EnTeQuAk** [comment]
PR: https://github.com/mozilla/amo-validator/pull/373
