### ISSUE TITLE
[fx44]  Show compatibility error if an add-on uses resource://(gre)?/modules/devtools

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/olympia#1165]
As explained in [bug 1203159](https://bugzilla.mozilla.org/show_bug.cgi?id=1203159), the devtools were moved to a different path, and this changed the resource paths for devtool JS modules. All instances of `resource://gre/modules/devtools/` and `resource:///modules/devtools/`  should be flagged.

This is a compatibility error, so the add-on shouldn't be upgraded in this case. It should also appear as a warning in regular validations.

Message:

The paths for all devtools JS modules have changed from resource://gre/modules/devtools/* to resource://devtools/*. See [this bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1203159) for more information.

Affected add-on: https://addons.mozilla.org/addon/jsonview/

Release timing: Firefox 44 will be released on January 26th.

**Comment by EnTeQuAk** [comment]
PR: https://github.com/mozilla/amo-validator/pull/375
