### ISSUE TITLE
Signing server sometimes ignores uploads via the signing API

### ISSUE THREAD

**Issue by minj** [mozilla/olympia#1166]
I have a custom upload script that searches for signed files with an exponential back-off, i.e. after 1,2,4,8,16 minutes (sum=31). However it keeps failing on some days. These days more than others.

It's not like 30 minutes is not enough either. I get emails once signing actually succeeds but I haven't got one today after two tries several hours apart.

I have some failed `pk`s for you (in the reverse chronological order):
```
f8f95552cc534a95a88cbeab16fae086
d08eca0625c4492ab7585acef436e601
ca5f2b2f0e1c434ca1e7d243ba270015
3f9f7922a6c04f85931dad70dba8673c
1a4c66d423a84a12a4b1efea750e87d2
7ab9248265384d57839a18f8ba57a009
```
My logs only go back 3 weeks at the moment but I had had more of these before that.

It would be nice if you made the server work more consistently.

---
I've now resorted to uploading the file via web interface. Nothing happened after pressing 'Add version'. After I tried again I got the 'version already exists' error. I can now see the upload but it's still faded out (active:false phase, presumably). 

Granted this might be an unrelated bug. Let's hope the signing completes before the next year comes ;)

EDIT: it was successful

**Comment by andymckay** [comment]
We think this is #1229 and that's being tracked in #1244
