### ISSUE TITLE
Remove recommendations from AMO

### ISSUE THREAD

**Issue by andymckay** [mozilla/olympia#1174]
Recommendations are show on about:addons:

https://www.dropbox.com/s/mm547te9vs1pmk9/Screenshot%202016-01-04%2013.12.50.png?dl=0

The actual recommendations aren't great and they don't get a huge amount of traffic. I don't think the feature is worth the effort. It would be nice if we could be certain how much traffic before making that call.

This might be a big bug but we should remove:
* the Recommended pane from about:addons
* the cron job that slows everything down
* everything in between

**Comment by jvillalobos** [comment]
Is this specifically about recommendations on about:addons, or in general? Featuring add-ons has historically given add-ons a noticeable boost in downloads and usage, but maybe that's more due to the blog posts.

**Comment by atsay** [comment]
Recommended add-ons seem to be different from Featured add-ons, which are chosen by the community board and get the boost in downloads. Methinks the boost comes from being on the homepage of AMO, blog post, social media promos, and Firefox & You newsletter.

**Comment by andymckay** [comment]
Recommendations, not features.

**Comment by vcarciu** [comment]
Verified as fixed : http://screencast.com/t/ajFdJHoI
