### ISSUE TITLE
Add-on homepage link doesn't work on dev

### ISSUE THREAD

**Issue by davehunt** [mozilla/olympia#1179]
The automation functional tests picked up an issue with the 'Add-on home page' link on dev. After clicking it the external page never loads.

Here's a screenshot of the [MemChaser](https://addons-dev.allizom.org/en-US/firefox/addon/memchaser/) add-on page with the link highlighted:
![screenshot_2016-01-05_13_48_56](https://cloud.githubusercontent.com/assets/122800/12116670/752c84ea-b3b3-11e5-8875-55b3645323b3.png)

The affected automated test can be found here: https://github.com/mozilla/Addon-Tests/blob/b9cd1da7e6e649a7d144469532e1616a844df5d3/tests/desktop/test_details_page.py#L94-L102

**Comment by andymckay** [comment]
@jasonthomas its connecting to https://outgoing-mkt-dev.allizom.org, which is timing out, is that server up?

**Comment by jasonthomas** [comment]
We were running a custom outgoing service on -dev, which is really not needed. I've updated the -dev settings to reflect a working instance we use for stage.

**Comment by davehunt** [comment]
Great, thanks! :)
