### ISSUE TITLE
Validator should check if the gecko object is specified in the manifest.json

### ISSUE THREAD

**Issue by krupa** [mozilla/olympia#1183]
## steps to reproduce:
1. Get a chrome extension from the Google store. Make sure to pick an extension with the same API support between Chrome and Firefox.
2. Change the extension to .xpi without making any other changes
3. Submit the add-on to https://addons-dev.allizom.org/en-US/developers/addon/submit/2
4. After validation is successful, click Continue

## expected behavior:
Validation fails and informs that gecko object is missing from the manifest.json

## actual behavior:
Validation passes. After clicking Continue, the user is stuck on Step 2 and is then notified that at least one supported application needs to be specified.

**Comment by andymckay** [comment]
Closed in favour of the issue in addons-linter.
