### ISSUE TITLE
No way to know if an add-on is prelim reviewed or not reviewed on versions page

### ISSUE THREAD

**Issue by magopian** [mozilla/olympia#1190]
There's no way currently to know if an add-on is preliminary reviewed (and thus signed and installable) or not reviewed at all, from its "versions" page.

See the screenshot below:
<img width="770" alt="screen shot 2016-01-06 at 10 35 51" src="https://cloud.githubusercontent.com/assets/167767/12139536/7186f7fe-b461-11e5-83ec-e7b46964361b.png">

**Comment by andymckay** [comment]
Duplicate of #1116
