### ISSUE TITLE
Carousel UI is broken on amo-dev

### ISSUE THREAD

**Issue by krupa** [mozilla/olympia#1220]
## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/

## observed behavior:
Carousel UI is broken on amo-dev

## screenshot:
https://www.dropbox.com/s/c94vhlhjo9g6j0e/Screenshot%202016-01-06%2009.17.44.png?dl=0

**Comment by muffinresearch** [comment]
Fwiw - I've backed out the styles refresh changes because it was getting in the way of testing jquery-migrate issues. See #1195.

It should be added back when it's more configurable so it doesn't affect ongoing issues whilst it's still in development.
