### ISSUE TITLE
Previews and icons have no Cache-Control: max-age/Expires headers set

### ISSUE THREAD

**Issue by diox** [mozilla/olympia#1222]
Our icons and previews return a `Last-Modified`, and have a query string cache buster in their URLs, but we don't set caching headers on them, so the browsers have to make an unnecessary HTTP request every time they come back, slowing down the page loads. It's probably also not helping the CDN to cache them properly.

Examples in prod:
https://addons.cdn.mozilla.net/user-media/addons/676061/preview.png?1450920015
https://addons.cdn.mozilla.net/user-media/addon_icons/620/620044-32.png?modified=1440451227

For more info: http://www.webpagetest.org/result/160106_16_R1Y/

**Comment by diox** [comment]
@jasonthomas can you look into that ? It should be just a matter of enabling super long expires for images.

**Comment by jasonthomas** [comment]
Changed landed on -dev and stage. I will update prod during our next code push.

```
λ master ~ → curl https://addons-stage-cdn.allizom.org/user-media/addon_icons/317/317263-32.png\?modified\=1400220147 -D- -so/dev/null
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: max-age=315360000
Content-Type: image/png
Date: Tue, 02 Feb 2016 19:21:36 GMT
Expires: Fri, 30 Jan 2026 19:21:36 GMT
Last-Modified: Sun, 22 May 2011 09:26:38 GMT
Server: nginx
X-Backend-Server: ip-172-31-54-77
Content-Length: 3163
Connection: keep-alive
```

**Comment by diox** [comment]
awesome, thanks!
