### ISSUE TITLE
Duplicate add-on ID found after failed add-on submission

### ISSUE THREAD

**Issue by nulledpointer** [mozilla/olympia#1261]
I filed it here as well: https://bugzilla.mozilla.org/show_bug.cgi?id=1237718.

STEPS TO REPRODUCE:
=============================

We are trying to sign our extension that is not hosted on AMO.
We created test AMO accounts (two accounts for two different extensions) to verify our extension before creating official AMO account and using that account to sign the same extension. Now using this official AMO account we get this error:
       >> X Your add-on failed validation with 1 error.
        >>  *Duplicate add-on ID found.

BTW, we are uploading via web interface
Could anyone please delete any ID associated with these test accounts? 

ACTUAL RESULTS:
=============================
addon validation throws following error :
X Your add-on failed validation with 1 error.
  *Duplicate add-on ID found.

EXPECTED RESULTS:
=============================
Extension should have been signed successfully.

**Comment by nulledpointer** [comment]
BTW, i was uploading via web interface

**Comment by nulledpointer** [comment]
BTW, i was uploading via web interface

**Comment by jvillalobos** [comment]
Please email amo-admins AT mozilla DOT org with the details, including the add-on ID.

(This issue can be closed)

**Comment by nulledpointer** [comment]
Thank you. I sent an email already.

**Comment by nulledpointer** [comment]
How will i know if duplicate addon- ID has been resolved?

**Comment by wagnerand** [comment]
When you get a reply?
Closing...
