### ISSUE TITLE
[AMO-Dev] New submited theme is not listed in Editor Tools pending queue

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/olympia#1278]
Steps to reproduce:
1. Sign in AMO-dev with an admin account https://addons-dev.allizom.org/en-US/
2. Upload a new theme (i.e. New-Theme-Color)
3. Go to Editor Tools and review the theme

Expected results:
The new submitted theme is listed in the pending queue.

Actual results:
The theme is not listed.

Notes/Issues:
Verified on FF43(Win 7). Issue is only reproducing on AMO-dev.
Screencast for this issue: http://screencast.com/t/F3I8Kjf9uUo
Don't know if is for sure a js error, but until it will be checked I am adding this to the tracker: #1197

**Comment by muffinresearch** [comment]
I don't see this being a JS error - I didn't see any JS errors through the submission process with persistent logs turned on.

I've just added a theme can you look for it in the queue I don't yet have admin on -dev? The slug is "my-test-theme-of-win".

**Comment by ValentinaPC** [comment]
There is something strange happening.
When I make a search after your theme slug... my themes are listed. 
Please see the screenshot: 
![2016-01-08_1808](https://cloud.githubusercontent.com/assets/15685960/12202527/07839a64-b633-11e5-91ca-74f0fac25b26.png)

Also, my themes and your theme are listed in the pending queue NOW. Maybe is a time/caching issue. On stage things happen instantly.

**Comment by andymckay** [comment]
At this point, we will have to ignore these timing problems on dev because the infrastructure is just different. That's a shame, I know, but let's worry about stage.
