### ISSUE TITLE
[AMO-dev] "Required Add-ons" option from Edit Listing->Technical Details is not working as expected

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/olympia#1279]
Steps to reproduce:
1. Load AMO-dev page https://addons-dev.allizom.org/en-US/firefox/
2. Go to any add-on Edit Listing page (i.e. https://addons-dev.allizom.org/en-US/developers/addon/password-categories/edit) 
3. Click "Edit" for Technical Details section
4. Go to "Required Add-ons" field, search and add an add-on

Expected result:
Any add-on can be added.

Actual results:
The add-on cannot be added.

Notes/Issue:
A js error is displayed in the console.
Verified on FF43(Win 7). Issue is only reproducing on AMO-dev.
Please see the screencast: http://screencast.com/t/20Z0wx9CRs
Tracker issue: #1197

**Comment by muffinresearch** [comment]
Good catch! - this is definitely a migrate removal issue.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF43(Win 7).
Postfix screenshot: 
![2016-01-13_1351](https://cloud.githubusercontent.com/assets/15685960/12293540/def67f4e-b9fc-11e5-9597-31f88a1bb89f.png)
