### ISSUE TITLE
Move some of the data out of FileUploads

### ISSUE THREAD

**Issue by andymckay** [mozilla/olympia#1287]
FileUploads contains lots of rows that we really don't need. Let's figure out what we don't need and delete them out of FileUploads to keep the table small and spry.

It's useful to have the validation data for the Validation team, so let's make sure we move it in to an archive table, or dump the data somewhere. @diox to provide more details.

Tracker #1244

**Comment by diox** [comment]
Discussed with @jasonthomas and he's going to make a dump of the table and put it in a restricted S3 bucket. We'll then delete the old rows (probably can delete everything from before say, September 2015)

**Comment by jasonthomas** [comment]
I've backed up the file_uploads table. Before we do the actual migration I will also do a manual RDS backup to capture the state of the database.

**Comment by diox** [comment]
Rows deleted on dev and stage in batches of 60k-120k. It was pretty fast except for the first one, I assume because it had to scan the whole table - "created" column is not indexed.

**Comment by diox** [comment]
Assigning back to jason since the rows that are left to delete are in prod. Stage and dev are done and the code to use the new PK is deployed there.

**Comment by jasonthomas** [comment]
This is done on prod.

**Comment by andymckay** [comment]
Done, thanks all.
