### ISSUE TITLE
Provide a CSP end point that won't kill us

### ISSUE THREAD

**Issue by andymckay** [mozilla/olympia#1289]
If we turn on CSP on AMO, we are concerned we might DOS ourselves like we have in the past. It would be nice to send CSP to a completely different end point that doesn't break things.

Was chatting to @jasonthomas about this and I think @jvehent might be able to help based on comments from #995.

**Comment by jvehent** [comment]
Discussed this with @jasonthomas and we can use the same CSP reporting logging setup in nginx that's being deployed for Hello. Reports will go into heka, then elasticsearch where devs can see them via Kibana.
The Olympia app will never see the reports, so the risk of DDoS is limited (it would have to ddos nginx, which is hard).

**Comment by andymckay** [comment]
Sweet, we are aiming to be able to test next week over to @jasonthomas to
set this up I guess?

**Comment by jasonthomas** [comment]
Yes, I will take care of the setup.

**Comment by muffinresearch** [comment]
FWIW The blocker label is just to note that this blocks completion of #995 *not* that it blocks a push.

**Comment by jasonthomas** [comment]
The CSP endpoint has been deployed on -dev and stage. CSP reports will end up elasticsearch/kibana. Once reports start coming in on -dev and stage I will configure the kibana dashboards.

**Comment by jasonthomas** [comment]
Deployed on -prod.
