### ISSUE TITLE
Log the "There was a problem contacting the server" error when adding a version

### ISSUE THREAD

**Issue by mstriemer** [mozilla/olympia#1309]
When adding a version to an add-on it sometimes fails with "There was a problem contacting the server" which is the JS client timing out. We should log this somehow so we know how often it is happening.

This may also be happening through the signing API at an unknown rate.

<img width="487" alt="screenshot 2016-01-06 16 34 26" src="https://cloud.githubusercontent.com/assets/211578/12241918/a69d79ce-b85b-11e5-83f2-49e6292ce81e.png">

Tracker: #1244.

**Comment by mstriemer** [comment]
The [error message is added](https://github.com/mozilla/olympia/blob/11a059ccc864220bc36e0ebe134d447406481081/static/js/common/upload-addon.js#L41) when the response from the server can't be parsed as JSON.

This makes me think that the row gets locked when we write the validation to the `FileUpload` and then a read during that time frame times out as it waits for the write to happen.

We currently poll this endpoint every second. I'm not sure how often this happens, maybe we can log it from JS somehow but we don't currently have support for that.

**Comment by andymckay** [comment]
We are now logging this into Raven JS.
