### ISSUE TITLE
Remove optimizely include. 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/olympia#1310]
Relates to #995

We're apparently not currently using it and since it currently breaks CSP we are going to remove it.

**Comment by marumari** [comment]
FWIW, I'm going to be working with cmore and Optimizely to try to make their code compatible with CSP over the next year. Hopefully this means that we don't have to choose between Optimizely and CSP in the future.

**Comment by magopian** [comment]
Oh wow, that would be awesome :heart_eyes:
