### ISSUE TITLE
Update review email templates

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/olympia#1316]
We're changing these templates and some of the canned responses to make them friendlier for developers, and also to update some information in them (in particular, the use of the term 'editors' and the review policy URL).

PR coming.

**Comment by wagnerand** [comment]
After this landed, https://bugzilla.mozilla.org/show_bug.cgi?id=1202071 can be closed.

**Comment by wagnerand** [comment]
https://github.com/mozilla/olympia/pull/1317

**Comment by erosman** [comment]
First note:  This one seems rather short
`<option value="Thank you!">Approved for Public</option>`

**Comment by Noitidart** [comment]
Looks great I like these new ones! Short and concise makes a lot of sense. :)

**Comment by kewisch** [comment]
I was a bit surprised about the short thank you messages too. I'd personally prefer for prelim positive 
```
Thank you! Please take care of the following issues for the next version:

1)
```
which can then be deleted, or just writing Thank you is quick enough.

**Comment by jvillalobos** [comment]
This issue is only for the email templates. For feedback on the canned responses, please reply to the email thread I started on the list.
