### ISSUE TITLE
Updates for web extensions are not showing up in the add-ons manager

### ISSUE THREAD

**Issue by krupa** [mozilla/olympia#1318]
## Firefox version tested on:
Firefox 43.0.4

## test webextension used:
https://addons-dev.allizom.org/en-US/firefox/addon/shutterstock-tab/

## steps to reproduce:
1. Install a web extension version from addons-dev 1
2. Make sure the web extension has an update which is approved and public
3. Tools -> Add-ons; check for updates

## expected behavior:
Update for webextension shows up

## actual behavior:
Updates for regular add-ons show up but updates for webextensions are not getting listed in the add-ons manager

## about:support info
https://pastebin.mozilla.org/8856416

## Console log:
https://pastebin.mozilla.org/8856415 is from the console. It clearly says  addons.update-checker      DEBUG Found an update entry for addon23@example.com version 1.2.3

**Comment by krupa** [comment]
Problem is also reproducible on the latest nightly. See https://www.dropbox.com/s/hda9bj12o0ew8lg/Screenshot%202016-01-12%2013.56.29.png?dl=0

Highlighted line shows that there is an update for the webextension i am looking at.

**Comment by andymckay** [comment]
Because I think this is in Firefox, moving over to Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1239109.

**Comment by andymckay** [comment]
See comments in the bug, if we set this add-on to 43.* it works because of strict compatibility checking.

**Comment by magopian** [comment]
I'm not sure what should be done here: I could make it so a WebExtension is set to 43-43.* if that's better, but if WebExtensions [aren't default to compatible](https://bugzilla.mozilla.org/show_bug.cgi?id=1239109#c2) (that's in Firefox? We don't do anything specific regarding D2C for WebExtensions on AMO), then we'll have the same issue as soon as 44 is out, right?

**Comment by magopian** [comment]
So, I think we want to close this in favor of #1339, please reopen if I'm wrong.
