### ISSUE TITLE
If application range is not specified in the manifest.json, it gets set to 42-42.*

### ISSUE THREAD

**Issue by krupa** [mozilla/olympia#1339]
## webextension used:
http://cl.ly/1f0J1Z0F1a2O

## url on stage:
https://addons.allizom.org/en-US/developers/addon/web-extensions-for-fun1/versions/1700173

## steps to reproduce:
1. Upload a webextension to stage. Make sure the manifest.json doesn't specify  the supported application range and just lists
"applications": {
  "gecko": {
    "id": "addon@example.com"
  }
}

2. Complete submission
3. Go to the version details page and check the supported range

## observed behavior:
By default, when no application range is specified, the range is getting set to 42-42* which means users on nightly won't get updates.

## screenshot:
https://www.dropbox.com/s/1mle9hqqn6at4cj/Screenshot%202016-01-12%2016.49.15.png?dl=0

**Comment by magopian** [comment]
What version should be used instead? Should it be the current nightly version? I believe in any case the version bumps that are run regularly (before each new release?) would update it. BTW, I don't think we've tested versions bumps with WebExtensions, have we?

**Comment by magopian** [comment]
I've just tried going to this url on nightly, and I can see the green install button (but then Firefox fails to install it: `1452678521731	addons.xpi	WARN	Download of https://addons.allizom.org/firefox/downloads/file/318877/web_extensions_for_fun1-4.2.8-fx.xpi?src=version-history failed: signature verification failed`, which I believe is not relevant to this issue).

So, I believe this is related to #1340, and isn't in fact a bug? I'm closing for now, please reopen if it is indeed an issue we want to fix.

**Comment by krupa** [comment]
This happens in prod as well. This means that users won't get updates on newer versions of Firefox because strict compatibility is enabled by default for webextensions.

**Comment by andymckay** [comment]
The suggestion from @kmaglione was to add in the value * to AMO. I'm not sure what @jvillalobos was planning to do. Would like to see this resolved, currently the flow for users isn't great.

**Comment by magopian** [comment]
I'm lost on this one. Is it linked (or duplicate?) with #1318?

**Comment by jvillalobos** [comment]
So, we would need to add * as a valid maxVersion in Firefox, and then on AMO set WebExtensions without a strict_max_version to have a maxVersion of *. I'm not sure if Firefox will handle this maxVersion correctly when it gets the data from AMO, so that will need testing. I think this is the way we should go, given the new compatibility behavior of WebExtensions.

**Comment by deadsquid** [comment]
@jvillalobos - is there a bug filed per your comment?

**Comment by magopian** [comment]
This is the bug, isn't it? I'd love some tips on testing how Firefox handles the maxVersion of `*` though.

**Comment by deadsquid** [comment]
@magopian - if it's a Firefox issue, it should be in bugzilla, no?

**Comment by deadsquid** [comment]
@magopian - sorry, I thought there was discussion around a change being needed in Firefox, but re-reading I see that it needs testing. Will go back to watching.

**Comment by magopian** [comment]
Yeah, I _think_ it's already working that way (accepting `*` in Firefox) on the client side.

**Comment by magopian** [comment]
This will also need a modification of the amo-validator to interpret `*` as "no max version": https://github.com/mozilla/amo-validator/issues/390

**Comment by magopian** [comment]
Dear QA team: please make sure a WebExtension with no specified `strict_max_version` can be properly submitted, has its max version automatically set to `*`, has its install button in public pages display correctly, and can be properly updated through about:addons update checks!
