### ISSUE TITLE
Version discrepancies

### ISSUE THREAD

**Issue by krupa** [mozilla/olympia#1340]
## steps to reproduce:
1. Compare the supported application range at https://addons.allizom.org/en-US/developers/addon/web-extensions-for-fun1/versions/1700173 to https://addons.allizom.org/en-US/firefox/addon/web-extensions-for-fun1/versions/

## expected behavior:
version range is consistent across dev pages and consumer pages

## actual behavior:
- status & version detail page lists it as 42-42.*
- versions on Public pages lists as 42 and later
- install button is enabled for users on 46.0a1 when it shouldn't be

<img width="1372" alt="version miss" src="https://cloud.githubusercontent.com/assets/301317/12281839/3f691a76-b94e-11e5-8da0-b4c39c7518da.png">

**Comment by magopian** [comment]
I could be wrong, but this has always been the case, and it's not related to WebExtensions. See https://addons-dev.allizom.org/en-us/developers/addon/tabsmackh/versions/1527539 and https://addons-dev.allizom.org/en-us/firefox/addon/tabsmackh/versions/.

I'm thus removing the label and closing this issue, unless this is something we want to change (but I'm not sure what the implications are... probably very complex, we'll need to ask Jorge).

**Comment by jvillalobos** [comment]
By default, add-ons are considered compatible with all future versions of Firefox. The maxVersion was useful before we implemented this, and it's still useful for add-ons that have strictCompatibility set in install.rdf.
