### ISSUE TITLE
JS error when tapping "Add to Firefox" button for any addon

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/olympia#1347]
Prerequisites: 
Set remote debugging for Android (https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE ) 

Steps to reproduce:
1. Load AMO-stage on your android device
2. Go to details page for any add-on
3. Tap "Add to Firefox" button
4. Observe the messages in the console

Expected results:
There are no issues.

Actual results:
"ReferenceError: _gaq is not defined" is displayed in the console.

Notes/Issues:
The add-on installation can be completed.
Verified on FF43(Android 5.0.1). Issue is reproducing on AMO-stage, dev and prod.
Screenshot for this issue:
![2016-01-13_1739](https://cloud.githubusercontent.com/assets/15685960/12299962/f80cb9c4-ba21-11e5-880d-6ea054944da5.png)

**Comment by muffinresearch** [comment]
Fwiw this is also reproducible when using the mobile site on desktop.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF43(Android 5.0.1).
Postfix screenshot: 
![2016-01-14_1137](https://cloud.githubusercontent.com/assets/15685960/12320821/716bdf52-bab3-11e5-87d7-ba230920b9f4.png)
