### ISSUE TITLE
Make syslog available

### ISSUE THREAD

**Issue by andymckay** [mozilla/olympia#1364]
In the light of issue #1363 jason is going to make syslog available somewhere, probably in S3 so we can get it at, will help #1244.

**Comment by jasonthomas** [comment]
Currently testing syslog on -dev. We should be able to deploy this to stage and prod during our next push.

**Comment by jasonthomas** [comment]
Enabled on -dev, stage and prod for the last few days. Logs are being synced to S3 and can be accessed using https://mana.mozilla.org/wiki/display/SVCOPS/AMO+Dev+Resources#AMODevResources-Syslog
