### ISSUE TITLE
Updates for add-ons are not displayed in about:addons

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/olympia#1380]
Steps to reproduce:
1. Load AMO-stage page https://addons.allizom.org/en-US/firefox/
2. Submit and approve an add-on (i.e. https://addons.allizom.org/en-US/firefox/addon/firebugssss/)
3. Install the addon
4. Add a new version for that add-on (approve it)
5. Go to about:addons and check for updates

Expected results:
The update shows up.

Actual results:
The update is not showing up. 

Notes/Issues:
The message "1452777868350 addons.update-checker WARN Update manifest for firebug1@software.joehewitt.com did not contain an updates property" is displayed in the browser console.
Please see the screenshot: 
![2016-01-14_1524](https://cloud.githubusercontent.com/assets/15685960/12325632/361e4a68-bad4-11e5-8bfb-aa603d924d01.png)

Verified on FF43(Win 7). Issue is also reproducing for webextensions.

URL used -> extensions.update.url; https://versioncheck.allizom.org/update/VersionCheck.php?reqVersion=2&id=addon23@example.com&version=1.2.2&maxAppVersion=*&status=userEnabled&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=43.0.4&appOS=Darwin&appABI=x86_64-gcc3&locale=en-US&currentAppVersion=43.0.4&updateType=97&compatMode=normal

**Comment by EnTeQuAk** [comment]
Verified with @ValentinaPC and found out that the URL was accidentally hard-coded in Firefox thus showing wrong results for different addons.

Thus closed as wontfix :smiley:
