### ISSUE TITLE
The "Contributions" link from Statistics page is not displayed in AMO-prod

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/olympia#1400]
Steps to reproduce:
1. Load Statistics page for an add-on in AMO-prod https://addons.mozilla.org/En-US/firefox/addon/firebug/statistics/?last=30
2. See the "Contributions" link 

Expected results: 
The link is displayed (and usable) under the "by Add-ons Status" link.

Actual results:
The link is not displayed.

Notes/Issues:
Verified on FF43(Win 7). Issue is reproducing on AMO-prod.
Screenshot for this issue: 
![4](https://cloud.githubusercontent.com/assets/15685960/12353849/811d577c-bb9a-11e5-9c4b-6290a386eb48.png)

**Comment by andymckay** [comment]
Access to Contributions is controlled by a different permission you don't have for firebug on prod.
