### ISSUE TITLE
UnicodeDecodeError when viewing collections with non-ascii display names

### ISSUE THREAD

**Issue by kumar303** [mozilla/olympia#1412]
Regression from upgrading cache-machine: https://sentry.prod.mozaws.net/operations/olympia-prod/group/206714/ Well, AMO is creating the cache key wrong so it was probably a bug all along that we never noticed.

STR:
- Change your display name to something with non-ascii characters
- Create a collection
- View the collection in a private window (so that you have fresh cookies, which affect cache somehow)

**Comment by kumar303** [comment]
Fixed in https://github.com/mozilla/olympia/pull/1410

**Comment by kumar303** [comment]
I don't know if these STR are exact but I can reproduce it on dev by opening this in a private window https://addons-dev.allizom.org/en-US/firefox/collections/dioxmat%E5%9B%9B%E5%A4%A9%E7%8E%8B%E5%AF%BA/%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%B5%D0%BD%D0%BE-%D0%BF%D0%BE%D0%BB%D0%B5%D0%B7%D0%BD%D0%BE/

**Comment by diox** [comment]
Yeah, that should be enough as STR. Need to wait for dev to deploy to see if my changes fix it.

**Comment by diox** [comment]
#1410 does fix it on dev.
