### ISSUE TITLE
Archive old stats onto disk

### ISSUE THREAD

**Issue by andymckay** [mozilla/olympia#1413]
To support #1395, let's take old stats for an add-on and place them onto disk somewhere (likely into whatever django uses for storage, which becomes S3 or something behind the scenes). This will examine the relevant tables in the database and write them out to a file.

It will then expunge the data from the database, once its sure the data is successfully on the file system :)

**Comment by magopian** [comment]
I was thinking, maybe it would make sense to write the data on the disk straight away, as we read the data from the disk (just before or just after storing everything in the DB)? I'll need to investigate that, but I believe the data is already properly filtered/categorized/sorted as we push it in bulk in the database, so it might be the best time to just store it on disk at the same time.

Bonus points:
- the data is available to the dev to download as soon as we have it
- we can remove the old data whenever we want (no need to time it precisely, if a cron misses, no big deal, no need to fiddle with dates and time deltas and what not)
We essentially decouple the two things: storing on disc and removing from the database.

**Comment by andymckay** [comment]
That sound pretty awesome to me. In that case we'll just need that custom command to clear out what we have now.
