### ISSUE TITLE
[CSP] Content Security Policy violation when loading add-on details page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/olympia#1453]
Relates to #995 

Steps to reproduce:
1. Load AMO-stage page https://addons.allizom.org/en-US/
2. Load any add-on details page (i.e. https://addons.allizom.org/en-US/firefox/addon/easy-copy/?src=cb-dl-featured) with the console opened (and Security tab checked)
3. Observe the console

Expected results:
There are no issues CSP related.

Actual results:
There is a CSP violation.

Notes/Issues:
The issue can be seen on Android too, when accessing pages, like: home, write a review, theme info. 
Please see the screenshot: 
![2016-01-20_1608](https://cloud.githubusercontent.com/assets/15685960/12451604/1abb7da4-bf93-11e5-9ef9-16982c3470f8.png)

**Comment by muffinresearch** [comment]
This looks to be only on the mobile site where we are inlining CSS.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev using FF43 (Android 5.0.1).
Postfix screenshot: 
![an](https://cloud.githubusercontent.com/assets/15685960/12476507/6ecf813e-c032-11e5-882f-ec412775bc1d.png)

Still reproducible on AMO-dev using FF43(Win 7) when loading add-on detail page.
Please see the screenshot: 
![desk](https://cloud.githubusercontent.com/assets/15685960/12476543/b6a18200-c032-11e5-9a8e-8291bb1967c8.png)

**Comment by muffinresearch** [comment]
@ValentinaPC could you file a new issue for this ^ - it's not the same warning. Assign it to me and I'll take a look.

**Comment by ValentinaPC** [comment]
Logged another issue. (see #1469 )
Closing this.
