### ISSUE TITLE
Discovery Pane layout is broken

### ISSUE THREAD

**Issue by madalincm** [mozilla/olympia#1456]
prerequisites: 
Change discovery pane to point to the stage server:
I  Go to about:config
II Modify the value of extensions.webservice.discoverURL to 
  https://addons.allizom.org/%LOCALE%/firefox/discovery/pane/%VERSION%/%OS%

1. Open the discovery pane (about:addons)

Expected results:
There are no layout or display issues.

Actual results:
The layout is broken.

Notes/Issues:
Verified in FF43(Win7) Issue can be reproduced in amo-stage.
Screencast for this issue: http://screencast.com/t/B0qFRwoUn

**Comment by muffinresearch** [comment]
Appears to be a regression from 9f3717fe89

**Comment by diox** [comment]
Yeah, I removed an extra `</section>` in that commit. I didn't see it locally because I didn't have enough add-ons for the main pane.

**Comment by muffinresearch** [comment]
@diox does this fix need to go on the cherry-pick list?

**Comment by diox** [comment]
Yeah, I added it to the etherpad.

**Comment by madalincm** [comment]
Verified as fixed in FF43(Win7) in addons-dev.allizom.org
It's still reproducing in stage but mat said it was not pushed to stage yet and he will ask to include this fix in today's push
