### ISSUE TITLE
Shows "Duplicate Add-on Id" error even when there is no other add on with the same id

### ISSUE THREAD

**Issue by pm-preeta-karmarkar** [mozilla/olympia#1465]
I got an add-on signed with following id -
adinspector@pubmatic.com

Then I deleted the same because it had some issues.

Now , I am trying to upload new add on with same id - adinspector@pubmatic.com

It is giving Duplicate Add-on Id error. Please resolve.

I did the same yesterday and it was working.But,today the same steps are not working.

**Comment by pm-preeta-karmarkar** [comment]
![errorwhilesubmitting](https://cloud.githubusercontent.com/assets/8835947/12477725/2dfaae70-c057-11e5-912c-d99d85600084.png)
![validationreportshowsnoerror](https://cloud.githubusercontent.com/assets/8835947/12477735/418578f8-c057-11e5-99c3-ae2df6753d4a.png)

**Comment by jvillalobos** [comment]
Please send an email to amo-admins AT mozilla DOT org with the details.

**Comment by pm-preeta-karmarkar** [comment]
I have sent an Email to amo-admins@mozilla.org. Wondering how they can help.
