### ISSUE TITLE
JS errors when trying to make a contribution

### ISSUE THREAD

**Issue by vcarciu** [mozilla/olympia#1466]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0

Steps to reproduce:
1.Open an addon with contributions
2.Try to contribute
3.Observe the console

Expected results:
No errors in console

Actual results:
Error: Permission denied to access property "toString"

Please see screencast for this bug : http://screencast.com/t/YRIyip1wV

NOTES:
I can see this warning too "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/" . Please let me know if a different issue is needed for this.

**Comment by muffinresearch** [comment]
I couldn't see this specific error initially but then I found this: https://stackoverflow.com/questions/13100611/replace-url-from-youtube-to-embed-code-error-permission-denied-to-access-prop

It appears to only be surfaced when flash is enabled. As such it's nothing that we can resolve.

> I can see this warning too "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/" . Please let me know if a different issue is needed for this.

Probably worth filing a separate issue for this (although it will be low priority) and we can investigate if there's an easy way to resolve it. I don't expect it will cause any issues as it's just a deprecation warning.
