### ISSUE TITLE
Deprecation warning when trying to make a contribution

### ISSUE THREAD

**Issue by vcarciu** [mozilla/olympia#1467]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0

Steps to reproduce:
1.Open an addon with contributions
2.Try to contribute
3.Observe the console

Expected results:
No warnings in console

Actual results:
"Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/" deprecation warning in console

Please see screencast for this bug: http://screencast.com/t/3PJBbrsH9x

**Comment by andymckay** [comment]
Its not reducing the experience in this case because we are opening a window on the click event. Given that this will be part of the re-write, I think we shouldn't do anything with this.
