### ISSUE TITLE
Remove 'block ID' note from add-on deletion page.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/olympia#1481]
After 0f72414, we need to change the add-on deletion dialog.

This is half reverting 9273e08 and half rewording that text.

Should be done by either me or @eviljeff whoever gets to it first.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF43(Win 7).
The block ID option from add-on deletion page is no longer available.
Please see the screenshot: 
![2016-01-22_1412](https://cloud.githubusercontent.com/assets/15685960/12510418/60fca722-c112-11e5-8a22-db4332052292.png)
