### ISSUE TITLE
Can't sign recompiled addon for private use

### ISSUE THREAD

**Issue by kolAflash** [mozilla/olympia#1507]
Hi,

I just recompiled the "develop" branch of this addon for Linux, to test it in my everyday Firefox usage.

https://gitlab.labs.nic.cz/labs/dnssec-validator/tree/develop

https://addons.mozilla.org/de/firefox/addon/dnssec-validator/

Sadly Mozilla doesn't seems to sign it.

https://addons.mozilla.org/en-US/developers/addon/submit/2

I didn't wrote that extension to I don't know anything about it's internals. I just want to test the current develop version of it.

**Comment by jvillalobos** [comment]
What do you mean that it can't be signed? Do you see an error message, did you receive a rejection email?

**Comment by gigelu** [comment]
I'm having the same problem, can't sign an addon for private use.

This is the message: http://i.imgur.com/B79dVtV.png

This is a discontinued addon, JSView, modified by me to work with the latest versions of Firefox.

**Comment by kolAflash** [comment]
@jvillalobos

I didn't got an E-Mail. Here are screenshots of the error messages.

As said, I don't know anything about the internals of the addon. I just compiled a Git version of it myself, to test if that fixes some problems the addon used to have.

![screenshot_001](https://cloud.githubusercontent.com/assets/3355089/12562928/ec68b692-c3a7-11e5-846b-79b4b3d92b14.png)
![screenshot_002](https://cloud.githubusercontent.com/assets/3355089/12562929/ec6af4ac-c3a7-11e5-87d6-e6b4b6c69c96.png)
![screenshot_003](https://cloud.githubusercontent.com/assets/3355089/12562930/ec6b84da-c3a7-11e5-9e55-d5fb9c1ec20b.png)

**Comment by jvillalobos** [comment]
@gigelu Please open a new issue for your case. We will need the XPI so we can test it ourselves.

@kolAflash You're getting a Duplicate UUID error. If you're creating a new add-on based on an existing one and want to get it signed, you need to come up with a new add-on ID and change the ID in the install.rdf file. If you need more help, you can ask in the [Discourse Forum](https://discourse.mozilla-community.org/c/add-ons).

**Comment by kolAflash** [comment]
@jvillalobos
Why there's no way to change the UUID on the signing website?

**Comment by jvillalobos** [comment]
The add-on ID is set in the install.rdf file of the add-on. You need to change that before uploading. The ID needs to be correctly set in the file because that's what tells AMO which add-on is which.
