### ISSUE TITLE
Admin contains inline script that's blocked by CSP

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/olympia#1508]
Relates to #995 

Not sure if this is a problem - but some small snippets of JS  are included inside &lt;script> tags on the Admin pages and are subsequently blocked by CSP.

Newer django admin pages will have the inline JS removed as of 1.10 [1] according to https://github.com/mozilla/django-csp/pull/49

**Comment by muffinresearch** [comment]
@magopian what do you think?

**Comment by magopian** [comment]
Not sure, what kind of js snippets? Are they required or just "nice improvements" like auto-focus? I think there's some javascript needed to select foreign objects iirc, but not sure if those use included js in <script> tags? 1.10 is far away, I don't think we'll be switching any time soon.

Is it possible to allow inline scripts only for the admin? A bit like "exclude prefixes", but only for a given header?

**Comment by muffinresearch** [comment]
Some examples are things like that otherwise it's initialization of actions like this for flags:

```html
<script type="text/javascript">
(function($) {
    $(document).ready(function($) {
        $("tr input.action-select").actions();
    });
})(django.jQuery);
</script>
```

**Comment by magopian** [comment]
yeah... things we might need, then...

**Comment by muffinresearch** [comment]
Sent an email to the internal dev list for feedback on impact.

**Comment by muffinresearch** [comment]
So I think the consensus was to leave this as it is for now and we'll deal with problems that come from this later. Roll-on django 1.10.
