### ISSUE TITLE
Upload XPI is failing with Basic checks with Error " Add-on missing manifest.  Error: All add-ons require a manifest file.

### ISSUE THREAD

**Issue by ShailendraMoyal** [mozilla/olympia#1530]
We have XPI file for Firefox adds on and have been using for last 5-6 years. Since FF43 stopped installed without having it signed with Firefox , I have been trying to sign it but everytime its giving an error Add-on missing manifest.

Error: All add-ons require a manifest file.
in validation. Please help. 

<img width="1208" alt="screen shot 2016-01-27 at 4 28 13 pm" src="https://cloud.githubusercontent.com/assets/16917052/12611453/9edb5a1c-c512-11e5-8d7d-bb02a254f4d3.png">

**Comment by jvillalobos** [comment]
Please attach or link to the XPI causing this error.

**Comment by ShailendraMoyal** [comment]
I am not able to attach here the zip file as well. 

Sent the file on email.

**Comment by ShailendraMoyal** [comment]
Any update on this ?

**Comment by jvillalobos** [comment]
Which email address was this sent to? I don't see it.

**Comment by ShailendraMoyal** [comment]
Done. Sent file on amo-admins@mozilla.org

**Comment by jvillalobos** [comment]
The file uploaded is failing validation because it doesn't have the manifest file in the root of the package.
