### ISSUE TITLE
Number of shares and posts about an addon are missing

### ISSUE THREAD

**Issue by vcarciu** [mozilla/olympia#1531]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0

Steps to reproduce:
1.Go to any addon detail page on MP-Stage
2.Click on Share this addon link 

Expected results:
Number of shares and posts on social networks are displayed

Actual results:
Posts and shares numbers are missing

Please see screencast for this bug : http://screencast.com/t/pSpTkpFc

NOTES:
Not reproducible on Prod

**Comment by magopian** [comment]
Hello Victor,

thanks for filing, but we decided to get rid of those share counts, see #1439
