### ISSUE TITLE
`update_url` in manifest.json causes validation process to hang

### ISSUE THREAD

**Issue by wagnerand** [mozilla/olympia#1536]
STR:

1. Use a webextension that has the following entry in `manifest.json`:
```
"update_url": "https://clients2.google.com/service/update2/crx"
```
2. Upload webext to AMO **stage**. Valentia says it's not reproducible on -dev.

(markdown is trying to be smart with list enumeration ¯\_(ツ)_/¯ )

Actual results:
Validation never finishes.

Expected results:
Validation should finish. Not sure whether we should fail saying that update_url` is forbidden or just ignore it

**Comment by wagnerand** [comment]
Here is the broken file:
[broken.zip](https://github.com/mozilla/olympia/files/108206/broken.zip)

Valentina found another file that also has a `update_url` but validation works for that file:
[working.zip](https://github.com/mozilla/olympia/files/108205/working.zip)

Validation worked for the broken file as well when I just removed the `update_url` from `manifest.json` and repacked it.

**Comment by ValentinaPC** [comment]
Deleting the update_url from the *third* webextension made it work, as well. 
Attaching it.
[Third.zip](https://github.com/mozilla/olympia/files/108268/Third.zip)

**Comment by magopian** [comment]
I've just tried validating (standalone and as a new add-on submission) the broken.zip file (renamed as broken.xpi), and it worked perfectly. Maybe a temporary issue with the validation celery workers?

**Comment by magopian** [comment]
Closing for now, please reopen if needed

**Comment by ValentinaPC** [comment]
"Hanging at validation" is happening again when trying to upload a new version for an add-on in AMO-dev FF43(Win 7).
Please see the screencast: http://screencast.com/t/h3v6QnulB7gi (I've also cleared the cache/cookies)
Attaching the add-on used (zip format
[test 2-01.02-jap.zip](https://github.com/mozilla/olympia/files/112069/test.2-01.02-jap.zip)
).
