### ISSUE TITLE
AMO wrongly identifies JPM addons as Jetpack Add-on

### ISSUE THREAD

**Issue by erosman** [mozilla/olympia#1540]
Unless there has been an unannounced change, AMO used to mark JPM packed addons as **Restartless Add-on** and CFX packed addons as **Jetpack Add-on**.
Above is the cause for fair amount of confusion.

Example:
```
https://addons.mozilla.org/en-US/editors/review/chnprice-search-for-aliexpres
https://addons.mozilla.org/en-US/editors/review/myfastbooking
https://addons.mozilla.org/en-US/editors/review/ma-full-screen
```

**Comment by wagnerand** [comment]
JPM packed add-ons are SDK based add-ons. The fact they didn't show up as such was a bug which has been fixed recently.

**Comment by erosman** [comment]
In that case.. it would have been **useful**  to announce these types of change.

**Comment by wagnerand** [comment]
It was a bug that just no one got the time to fix yet. It shouldn't make any difference to any reviewers, because JPM packed add-ons were SDK add-ons from the start.

**Comment by erosman** [comment]
It should be apparent from the content of this post that it DID make a difference.

**Comment by wagnerand** [comment]
It is not apparent. Please elaborate.

**Comment by erosman** [comment]
I made a post... because there was a reason for making a post.
You say, it is not apparent.
Why did you think I made the post?

I used the information displayed on the reveiw page and based my review upon that information.
The information had changed and that resulted in an erroneous review.
The situation should have been apparent, If you have checked those links.

Let me simplify it:
Previously, only addons packed with CRX where marked as Jetpack Add-on.
All addons packed with CRX should be rejected due to the bugs.
Based on above information, addons marked as Jetpack Add-on were rejected.

Olympia changed without any notification...

The point is not whether JPM are SDK addons or not. I know that they are.
The point is that previous they were not marked as Jetpack and that lead to a wrong review.

The final point is that ... if such things happens, please notify reviewers so that developers wont be faced with inconvenience of wrong review result.

**Comment by wagnerand** [comment]
My email about the rejection of cfx clearly stated how such add-ons are identified, i.e. by the typical `resources` folder and an unrecognized `bootstrap.js`.

None of those criteria were given for the second and third add-on you mentioned. The first one has been deleted.

**Comment by erosman** [comment]
I am familiar with the process of identifying bootstrap.js

The point of this topic is the information that is displayed on the review page.

**Comment by wagnerand** [comment]
On what page exactly? On the queue page,  on the review details page for that add-on or on the code browser page? What exactly changed?

**Comment by erosman** [comment]
On the actual addon review page ie:

> Categories
>     Appearance
>     Social & Communication
> 
> Flags
>     Jetpack Add-on

**Comment by wagnerand** [comment]
This should not affect the review at all. As I said, JPM based add-ons were Jetpack add-ons from the start, no one just had the time to fix the issue that they are not marked as such.

With or without this flag on the review page, the review should have exactly been the same. `bootstrap.js` was recognized by the validator (before and after the change) and there was no `resources` folder (before and after the change).

**Comment by erosman** [comment]
Again, I used THAT information and THAT information lead me to the WRONG conclusion, and the point of this topic is THAT information (not how should an addon be reviewed).

**Comment by wagnerand** [comment]
Well your decision should have been based mostly on the code and partly on
the validator warnings.

**Comment by erosman** [comment]
> Well your decision should have been based mostly on the code and partly on the validator warnings.

Again you are arguing **review procedure** and diverting from the fact that changes made to the Olympia should have been notified.

I have written a large number of scripts that use the information available.
If the information available is changed, reviewers should be notified.

There was a bug ... you fixed it ... very good ... let us know ... that is all.

**Comment by wagnerand** [comment]
I did not think about having to announce this at it is a minor bug fix that
has no effect in policies or review decisions, or at least it shouldn't
have.
We also don't announce when we add new hashes to our known libraries list,
because it's a minor thing and there is no disadvantage of not knowing it
upfront.

My time is already spread super thin, I put in extra hours to clear up the
queues and to write patches like this one.
Unfortunately I don't have time to announce each and every small change. Of
course have been and will keep announcing changes that affect reviewers.

You are very welcome to follow along the issues, pull requests and commits
to this repository (and the amo-validator one). I believe Github even
provides RSS feeds, at least there are email notifications for issues and
PRs.

**Comment by erosman** [comment]
I understand that you may not have the time but such tasks could be relegated to those who have the time. Nonetheless, whether you have time or not is not relevant.
I noticed an issue and I reported it.

You seem to have enough time argument anything that I say... but not have the time to inform reviewers of information that may be useful to them.

Once again as with most of the bugs that I have filed (many which were closed without consideration and some that have been outstanding for 6+ months) ....

I spent my unpaid & volunteered time and effort reporting the issue.
You can do whatever you wish with the information provided.
