### ISSUE TITLE
Change timezone to UTC

### ISSUE THREAD

**Issue by wagnerand** [mozilla/olympia#1560]
Currently, the timezone in olympia is "America/Los_Angeles" which creates issues with displaying dates, for example the wait time for add-ons in the review queue.

Most of the code is not timezone aware, some small pieces are. There is even some timezone translation for ES going on, even though `USE_TZ` is _false_. The prod server itself runs on UTC.

So, let's change the timezone to UTC?!

**Comment by diox** [comment]
:+1:

It seems `settings.TIME_ZONE` matters when saving objects in the db, even if `USE_TZ` is `False`. We should be in UTC, so we should fix the setting.

**Comment by jasonthomas** [comment]
+1

**Comment by EnTeQuAk** [comment]
If we saved datetimes wrong in the database so far, which we apparently did i'm -1 changing this rapidly but we might think of if there's any consequence simply changing this.

**Comment by wagnerand** [comment]
@EnTeQuAk I had the same concerns but @diox said we can't make it any worse than it already is.

**Comment by andymckay** [comment]
Please see https://bugzilla.mozilla.org/show_bug.cgi?id=922922 for some discussion on this.
