### ISSUE TITLE
CSP error while attempting to make a contribution

### ISSUE THREAD

**Issue by krupa** [mozilla/olympia#1564]
## steps to reproduce:
1. Load https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/?src=ss
2. With the console open, click on the Contribute button
3. Check the console for any CSP errors

## observed behavior:
Console shows the following CSP error: 

Content Security Policy: The page's settings observed the loading of a resource at https://ic.paypal.com/webapps/adaptivepayment/flow/expresscheckoutincontextremembermeflow?execution=e1s2 ("frame-src https://addons.mozilla.org https://www.paypal.com https://www.google.com/recaptcha/"). A CSP report is being sent.

## screenshot:
https://www.dropbox.com/s/er7hw15qbcp448z/Screenshot%202016-02-01%2009.55.31.png?dl=0

**Comment by andymckay** [comment]
Blocks #995

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev and AMO-prod using FF45(Win 7),
Postfix screenshot:
![2016-03-15_1001](https://cloud.githubusercontent.com/assets/15685960/13771236/16b9140a-ea95-11e5-8eda-ea6d20a7c729.png)
