### ISSUE TITLE
[CSP] violation when making a search in Dev Hub page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/olympia#1578]
Relates to #995

Steps to reproduce:
1. Load AMO-prod Dev Hub page https://addons.mozilla.org/en-US/developers/
2. Make a search with web console opened (!Security tab)

Expected results:
There is no CSP violation in the console.

Actual results:
There is a CSP violation displayed in the console.

Notes/Issues:
Please see the csp reporting via network: https://pastebin.mozilla.org/8858317
Verified on FF44(Win 7). Issue is reproducing on AMO-prod.
Screenshot for this issue: 
![2016-02-02_1209](https://cloud.githubusercontent.com/assets/15685960/12746550/ea15e1ac-c9a7-11e5-8386-70e1dbf69df8.png)

**Comment by muffinresearch** [comment]
This one is a bit of a blocker. Despire configuring CSP to enable each violation I then found that Google's custom search (or the version we're using) uses eval. This one we can't configure our way around because it would make the CSP policy pretty much redundant.

**Comment by andymckay** [comment]
Blocks #995

**Comment by andymckay** [comment]
Chatting to @muffinresearch, we can have the same functionality but just not show the results in the AMO page, so we'll just bounce the results out to google to show in a seperate page.

**Comment by jvillalobos** [comment]
Can we modify the custom google search to include the discourse forum?

**Comment by muffinresearch** [comment]
> Can we modify the custom google search to include the discourse forum?

We can't use a custom google search at all unles it works without eval.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF44(Win 7).
Postfix screencast: http://screencast.com/t/FRIakrTarheU
