### ISSUE TITLE
Recently viewed collections list is not changed accordingly after switching users

### ISSUE THREAD

**Issue by vcarciu** [mozilla/olympia#1582]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0

Steps to reproduce:
1.Login and go to https://addons.mozilla.org/en-US/firefox/collections/
2.Log out and login again with a different user

Expected results:
The list of recently viewed collections is changed for the new user(or at least it is empty)

Actual results:
The list is populated with the recently viewed collections from the users logged at step 1

Please see screencast for this bug : http://screencast.com/t/p7PthSogOoi

**Comment by andymckay** [comment]
I can't really see a need for this and I'm not sure how its implemented, want to remove it? It also appears on each collection page.

**Comment by diox** [comment]
It's implemented using `localStorage`, that's why it's persisting like this. Let's just kill it.

**Comment by deadsquid** [comment]
It's less a need and more of a navigation assistance for your viewing history. It's a nice-to-have, and I'm not convinced this is actually broken, given the majority of AMO browsers are end-users without a login, but rather a use case that wasn't considered. It's definitely a bug if we feel the history should be separated by user in a browser.

Not making the case for keeping it, agree it's of limited value given how many people actually use collections these days (something we should also verify), but the convenience factor is nice to have, and we should look at how we manage breadcrumbs as a whole for AMO.

**Comment by deadsquid** [comment]
(so, yes, kill it. and we need to look at how/if we implement breadcrumbing AMO-wide as a separate item)

**Comment by vcarciu** [comment]
Verified as fixed : http://screencast.com/t/Kg9D2K2w
