### ISSUE TITLE
Review page for add-on with no versions returns 500

### ISSUE THREAD

**Issue by wagnerand** [mozilla/olympia#1585]
Trying to access a review page for an add-on that has no versions (because all of them have been deleted) returns a 500 error.

https://sentry.prod.mozaws.net/operations/olympia-prod/group/213041/

**Comment by magopian** [comment]
This should only happen if you're already viewing the review page while the version is being deleted, right?

I'll make it so it returns a 404 instead.

**Comment by wagnerand** [comment]
No, I can refresh the page as often as I want to, it will always display 500.

**Comment by magopian** [comment]
Yes, but this page isn't linked anywhere, once the versions are gone. Or is it?
The only way I can reproduce is going on the review page, and *then* delete the versions. If I delete the versions first, then there's no link to the review page anywhere in the editor tools.

**Comment by wagnerand** [comment]
Ah yeah. The point is that it does not matter whether there is a link pointing to a review page or not. In the vast majorities of cases, there is no link to the review page, yet (admin) reviewers need to access them for whatever reason.
The only case where there actually is a link to a review page is if that add-on is pending review.

Returning 404 is better than nothing, but I don't see why we cannot just change the review page with an empty versions block. 404 would indicate that this add-on does not exist which is not true.

**Comment by jvillalobos** [comment]
It could be useful to still have access to that page, but you would also need to make sure that no review actions can be taken, since those are linked to versions. Either way, the add-on can still be inspected by super reviewers using the /manage/ page, so I don't feel like it's such a big loss to return a 404.
