### ISSUE TITLE
CSP error on disco pane

### ISSUE THREAD

**Issue by krupa** [mozilla/olympia#1596]
## steps to reproduce:
1. Tools -> Add-ons
2. Check console for any CSP related errors

## observed behavior:
Content Security Policy: The page's settings observed the loading of a resource at https://addons.mozilla.org/en-US/firefox/addons/buttons.js?b=01ef2c4-56a7a899 ("script-src https://services.addons.mozilla.org https://www.paypalobjects.com https://apis.google.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://ssl.google-analytics.com https://addons.cdn.mozilla.net"). A CSP report is being sent.

## screenshot:
https://www.dropbox.com/s/mnwn9ccp88yb9j7/Screenshot%202016-02-02%2010.46.03.png?dl=0

**Comment by andymckay** [comment]
Tracking #995

**Comment by muffinresearch** [comment]
Duplicate of #1555
