### ISSUE TITLE
CSP error displayed when playing a video from promo banner in disco pane

### ISSUE THREAD

**Issue by vcarciu** [mozilla/olympia#1601]
Relates to #995

Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0

Steps to reproduce:
1.Go to about:addons
2.Click "Watch the video" button from "First time with Add-ons?" promo banner
3.Observe web console

Expected results:
No CSP errors

Actual results:
CSP error displayed as in the screencast from below

Please see screencast for this issue : http://screencast.com/t/xVcbQmLJ

**Comment by muffinresearch** [comment]
I don't have that banner and I can't seem to make it appear with a new profile either.

**Comment by muffinresearch** [comment]
This should be testable on -dev and stage with the following disco pane hosts:

dev: https://addons-dev-services.allizom.org/
stage: https://addons-services.allizom.org/
