### ISSUE TITLE
Close link in about:addons image lightbox has broken CSS.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/olympia#1606]
See https://services.addons.mozilla.org/en-GB/firefox/discovery/addon/ecosia-the-green-search/?src=discovery-featured

Looks like the sr-only css is in the wrong place to be included for the disco pane:

![ecosia_ _the_search_engine_that_plants_trees_____add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/12789552/4105a288-ca96-11e5-989f-3cb1e4753f25.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-prod FF44(Win 7).
Postfix screenshot: 
![2016-03-08_1637](https://cloud.githubusercontent.com/assets/15685960/13605545/b660a562-e550-11e5-8ddb-c691c131aae4.png)
