### ISSUE TITLE
JS error after Add-on icon click followed by page refresh

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/olympia#1608]
Steps to reproduce:
1. Load AMO-stage details page for any add-on (with JS tab opened in the web console)
2. Click Add-on icon
3. Refresh the page

Expected results:
There are no issues.

Actual results:
There is a JS error displayed in the console.

Notes/Issues:
Verified on FF44(Win 7). Issue is reproducing on AMO-stage, dev and prod.
Please see the screenshot:
![2016-02-03_1910](https://cloud.githubusercontent.com/assets/15685960/12790310/5cb0cf30-caaa-11e5-96d6-ab343d6d764a.png)

**Comment by muffinresearch** [comment]
This is the line causing the exception: https://github.com/mozilla/olympia/blob/master/static/js/impala/global.js#L125

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF44(Win 7).
Postfix screencast: http://screencast.com/t/dMXM3ujUh4
