### ISSUE TITLE
Can't submit update using Firefox Developer Edition

### ISSUE THREAD

**Issue by jyavenard** [mozilla/olympia#1615]
When I try to submit an update, I click on "Select a file..."

which then tells me "Finished validation aboutmedia.xpi" 100% complete and that it was validated with no errors and 2 warnings.

When I then click on "Add Version", nothing happen but at the type I can see "The submitted file is empty".

I could do the exact same procedure to submit a new xpi, just not update it.

**Comment by jyavenard** [comment]
This happens when using Firefox developer edition.
I attempted then to submit using chrome , and it worked just fine, no error message about the file being empty :(
now that is sad

**Comment by magopian** [comment]
Firefox dev edition is Firefox 46, which has an open bug about that: see https://github.com/mozilla/olympia/issues/1503#issuecomment-175101511

**Comment by jyavenard** [comment]
the culprit was lastpass 4.0 add-on.
After disabling it, things are working properly
