### ISSUE TITLE
Inform users for how long are they blocked after entering wrong FxA password many times

### ISSUE THREAD

**Issue by vcarciu** [mozilla/olympia#1623]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0

Steps to reproduce:
1.Go to AMO-dev and try to login through FxA
2.Enter wrong password many times until a message saying that "Attempt limit exceeded"

Expected results:
Users should also be informed for how long are they blocked

Actual results:
This info is not displayed

**Comment by andymckay** [comment]
Can you please file this over in Firefox Accounts? https://github.com/mozilla/fxa
