### ISSUE TITLE
Unused, possibly dangerous code?

### ISSUE THREAD

**Issue by amuntner** [mozilla/olympia#842]
https://github.com/mozilla/olympia/blob/master/apps/translations/forms.py#L56

    def as_ul(self):

etc

Initial investigation result is that this is dead/uncalled code.

My concern is that if it gets returned to something else and modified, it will not be mark_safe anymore.

**Comment by magopian** [comment]
Hello @amuntner,

I might have missed something, but the content of the `li`s [is escaped](https://github.com/mozilla/olympia/blob/master/apps/translations/forms.py#L66), so the code should be ok?

If it does get modified, and is not marked as safe anymore later on, then that's the caller responsibility, and in any case isn't a security issue (the opposite, "marking something unsafe as safe", would be a security issue).

**Comment by magopian** [comment]
Closing, if I missed something, please reopen!
