### ISSUE TITLE
Add a CSRF token to the FxA state parameter

### ISSUE THREAD

**Issue by mstriemer** [mozilla/olympia#866]
This isn't done in zamboni so we have no reference but it is considered a best practice to include some state that is also stored in the user's session in the state parameter passed to FxA. This way we can verify that the authentication request was generated by the app and not a third party. We should include some signing of the state parameter as well.

**Comment by kumar303** [comment]
The fact that Zamboni doesn't do it could be a bug.

**Comment by mstriemer** [comment]
Once we support changing the user's email address in #982 this will definitely be needed as without it clicking a link like `https://addons.mozilla.org/api/v3/accounts/authorize/?code=codeforattackersaccount` would cause the currently logged in user's account to transfer to the attacker's account.

I have some code that I wrote to put the current user's ID in the state parameter but I think we should instead just use a CSRF style token since that will have the same end result. The code should work for this it just needs to set a token instead of the user's ID.

**Comment by mstriemer** [comment]
My code is in https://github.com/mstriemer/olympia/tree/set-fxa-state-on-body.
