### ISSUE TITLE
Waffle old registration system

### ISSUE THREAD

**Issue by mstriemer** [mozilla/olympia#869]
We should wrap the old registration process in a waffle so that it can be turned off once #867 is completed to allow registration with FxA.

**Comment by ValentinaPC** [comment]
AMO is using the old registration method when trying to register from Extensions details page -> Add to collection -> Create a new add-on account.
Please see the screencast: http://screencast.com/t/1vipgXtrEQ
Verified on AMO-dev FF43(Win 7).

**Comment by mstriemer** [comment]
This should just redirect to FxA on the server side.

**Comment by ValentinaPC** [comment]
Also the "I don't have an account" link redirects to the old registration form.
Please see the screencast: http://screencast.com/t/wkpT789mL

**Comment by mstriemer** [comment]
The register page now renders the login view when the `fxa-auth` flag is active. This was fixed in https://github.com/mozilla/olympia/pull/1437.
