### ISSUE TITLE
Display issues for theme name if it contains numbers

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/olympia#902]
Steps to reproduce:
1. Sign into AMO-stage https://addons.allizom.org/en-US/firefox/   
2. Go to Tools->Submit a New Theme
3. Give your theme a name that contains numbers/special_chars (i.e. 3Theme)
4. View listing for the submitted theme

Expected results:
There are no display or layout issues.

Actual results:
The numbers/special_chars are not aligned with the rest of the name.

Notes/Issues:
Verified on FF42(Win 7). Issue is reproducing on AMO-stage, dev and prod.

![2015-11-10_1026](https://cloud.githubusercontent.com/assets/1514/11115243/0fb8bb44-8922-11e5-98d0-a29ff5d7d90c.png)

**Comment by muffinresearch** [comment]
This is not really a bug per se, as ascenders and descenders are a feature of the font used which is Georgia. If this is a problem then really we should change the font. I agree it looks unexpected.

<img alt="georgia _-_webfont___desktop_font_ _myfonts" src="https://cloud.githubusercontent.com/assets/1514/11115181/a89a0ad0-8921-11e5-9a07-44848b3cd1f6.png">

**Comment by muffinresearch** [comment]
I'm going to close this for now - but if anyone feels strongly we should change the font then we'll need to talk to UX.

**Comment by ValentinaPC** [comment]
Not reproducible after style-refresh.
I'll mark this fixed.
