### ISSUE TITLE
Integrate performance testing to find regressions

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/olympia#906]
I just found out about http://pytest-benchmark.readthedocs.org/en/stable/ and given the fact that we're planning on doing lots of refactoring and updates I was wondering if it would make sense to get this integrated somehow to see how we're doing.

I doubt it'll be easy to integrate with CI but at least with a small shell script and git we should be able to get reliable performance graphs.

Any ideas on that? @andymckay @magopian 

Example: http://pytest-benchmark.readthedocs.org/en/stable/comparing.html

**Comment by magopian** [comment]
I'm all for data, measurement and graphs ;)

**Comment by andymckay** [comment]
With what @kumar303 and @mstriemer for submissions, I think we've got this. Are you thinking of something more?

**Comment by kumar303** [comment]
We have https://github.com/mozilla/amo-loadtest but it's not automated. It would be nice to have something automated so we can track speed regressions. I assume that loadtest will be unrunnable very soon (actually I know it will stop working the minute FxA gets turned on!).
