### ISSUE TITLE
Inform users of ongoing service issues.

### ISSUE THREAD

**Issue by Caspy7** [mozilla/olympia#908]
Yesterday AMO experienced outages and poor load times.
A blog post was made to acknowledge this, but it was observed that a very small number of those affected probably saw this.
We need a site-wide method to notify users should something similar happen again.  A simple colored bar with text across the top of the site would probably work well.

**Comment by muffinresearch** [comment]
This is a good idea. Serving self-contained static pages for 5xx HTTP responses would be a good place to start. The 503/502s seen yesterday were blank.

**Comment by Caspy7** [comment]
My suggestion was not just for when the site is down.
I don't think the static 5xx pages are necessarily sufficient.
Yesterday the site didn't load for some, but at other times (or for other users) it was loading very slowly.  I loaded up the themes site and the images for theme previews were not loading in the browser (probably just downloading very slowly.
So my suggestion with the notification bar was meant to cover times when the site is performing poorly and we need to acknowledge it.  (Granted, we *hope* we'd never experience that again, but things happen.)

There might also be an argument for having this functionality (a site-wide notification bar) on hand for other purposes beyond performance or downtime issues.

**Comment by muffinresearch** [comment]
@Caspy7 ah ok - I misunderstood what you were saying in the initial description. Thanks for clarifying - I'll reopen the other issue as it's not a dupe.

**Comment by andymckay** [comment]
We have https://status.mozilla.org to inform of outages. We've coped without this for a whole lot of years, I'm not sure this is needed.

**Comment by anaran** [comment]
@andymckay Isn't the more important question whether the number of users and developers coping with this is increasing or decreasing? Those inside an organisation, using the services on a daily basis, will always be able to cope, but what's the impression given to external users?

**Comment by anaran** [comment]
@andymckay would be great if the site under heavy load would suggest to check https://status.mozilla.org which not every user will know about.

**Comment by andymckay** [comment]
I would much rather the site worked under heavy load, defining "heavy load" automatically isn't that easy so then we are left with a manual process to define some that I'm not clear has any end user value.

**Comment by tofumatt** [comment]
This strikes me as a "fun engineering task" that doesn't deliver as much value as just working to make the site perform better under heavier load, like @andymckay said.

Better 5xx pages would be nice though; when things were down yesterday there wasn't much user info. That seems like an easy thing to make/hook up and worth it for the (hopefully rare) times we're down.

**Comment by muffinresearch** [comment]
> We have https://status.mozilla.org to inform of outages. We've coped without this for a whole lot of years, I'm not sure this is needed.

Doesn't look like status was updated earlier in the week - that's a different issue but still...

![mozilla_status_-_all_services_online](https://cloud.githubusercontent.com/assets/1514/11144497/f7d790da-89f4-11e5-9997-a8f6fecb2bf2.png)

But we ensure status.m.o gets updated that's probably a good resolution to this issue as long as we have a link to it on every page e.g. in the footer or something.

Static 5xx errors can be dealt with via #910

**Comment by muffinresearch** [comment]
@tofumatt had a good point that the status page not being updated might be due to the fact we've just moved data centers. I'll file an ops bug for that.

**Comment by muffinresearch** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1224576

**Comment by andymckay** [comment]
I think we are mostly in agreement that this isn't worth the effort.

**Comment by muffinresearch** [comment]
I've filed a separate bug for adding a status link in the footer. I think we should at least address that. See #923
