### ISSUE TITLE
Change delete add-on form

### ISSUE THREAD

**Issue by andymckay** [mozilla/olympia#920]
The delete add-on form currently requires you to enter your password. In a world where passwords are all stored on FxA, that's not going to work, we'll have to come up with something different. We could force FxA authentication or just require something else typed in like the add-on GUID or something.

https://www.dropbox.com/s/97n8gnxodackle1/Screenshot%202015-11-13%2011.22.22.png?dl=0

**Comment by kumar303** [comment]
It seems like entering a password isn't necessarily required for what this form is trying to do

**Comment by mstriemer** [comment]
We could make it so the user needs to type in the slug for the add-on. That should make it a bit more clear what add-on they're deleting to prevent accidents.

Forcing FxA authentication doesn't sounds totally required.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF44(Win 7).
Postfix screencast: http://screencast.com/t/My2h95bwFV
Closing bug.
