### ISSUE TITLE
Log stats about FxA

### ISSUE THREAD

**Issue by mstriemer** [mozilla/olympia#934]
We should collect some stats:

* [x] FxA login success
* [x] FxA login failure
* [x] Request time to get bearer token
* [x] Request time to get profile
* [x] Total verification time (token + profile)

**Comment by kumar303** [comment]
in addition to stats it would be nice to also have some syslog messages for simple debugging (which is different from using stats for monitoring)

**Comment by mstriemer** [comment]
There was some logging added in #938 so we should just need stats now.
