### ISSUE TITLE
Prevent double-submit of forms

### ISSUE THREAD

**Issue by Rob--W** [mozilla/olympia#937]
Due to the slowness on AMO or unstability of my network connection, my forms gets submitted more than once. This results in duplicate review actions or messages.

Could you add something to prevent double-submit? If possible, check whether someone else has already posted an update before accepting the form (e.g. show "This add-on review has been updated. Please check whether your comment/review/approval/rejection is still relevant." when another message has been added since the last post).

This check could be at the Python backend, or part of the front-end (perform an (ugh) synchronous AJAX request upon submit, and only confirm the request if the last message hasn't changed; this only works if the server immediately replies, but I've noticed that AMO suffers from an aggressive cache, so this idea does not work...).

**Comment by andymckay** [comment]
It's rare to see a double form submit prevention scheme that isn't crappy. Doing this requires a bit of work and something I hesitant to recommend we work on. Especially because we plan on re-doing the entire front end of AMO next year to have a different structure, this is one of those things that wouldn't last the transition.

**Comment by andymckay** [comment]
Closing based on last comment.

**Comment by Rob--W** [comment]
@andymckay 
I agree that a general form submission prevention scheme takes a lot of work and rarely results in the desired result, that's why I scoped this bug report to the use case. At the review dashboard on AMO, I frequently see double (and triple!!!) submissions (not just by others, I also commit multiple submissions due to the lag on AMO). The URL is at https://addons.mozilla.org/en-US/editors/review/[addon-id]`

The back-end logic would be something along the lines of:

1. At form creation time: Include an identifier of the last message (all messages are printed, so this comes at no cost).
2. At form submission: Query the last row of the message sequence.
3. If 2 differs from 1, show the form again and ask the user to confirm the submission.

If implemented at the front-end, then I would do:

1. At `form.onsubmit`, use `event.preventDefault()` and request the page using AJAX.
2. If the last item in the form is equal to the current last element, use an unchecked `form.submit()`.
3. Otherwise show a warning and request a confirmation.

In both implementations I assume that the data is up-to-date (and not some old cached value).

The logic is not that difficult. If I knew a bit more about the stack that you're using for the backend, then I would have submitted a patch. Given that you're already familiar with the code, is it possible to fix it?
