### ISSUE TITLE
Add an icon in the queue for webextensions

### ISSUE THREAD

**Issue by magopian** [mozilla/olympia#940]
The same way we have icons for restartless or jetpack add-ons.

See the "Flags" column below:
<img width="976" alt="screen shot 2015-11-17 at 11 39 18" src="https://cloud.githubusercontent.com/assets/167767/11209187/008f7e6c-8d20-11e5-818a-8be0b201337b.png">

This will need https://bugzilla.mozilla.org/show_bug.cgi?id=1219772 first (which depends on #885)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF43(Win 7).
Postfix screenshot:
![2015-12-16_1438](https://cloud.githubusercontent.com/assets/15685960/11841123/a97bd04e-a403-11e5-9c4f-9fcd968134ed.png)
Closing bug.
