### ISSUE TITLE
Send WebExtensions off to manual review

### ISSUE THREAD

**Issue by andymckay** [mozilla/olympia#942]
Because we aren't quite sure what we need to validate or look at in WebExtensions, it was suggested that instead we just WebExtensions off for manual review on AMO.

**Comment by magopian** [comment]
Since #1005 we automatically review and sign unlisted extensions.
Do we want unlisted WebExtensions to also go to the manual review?

**Comment by jvillalobos** [comment]
Unlisted WebExtensions can't be any riskier than regular ones, so I think they should be auto-approved like the others.

**Comment by andymckay** [comment]
Since all listed add-ons are reviewed, I think we can just close this?
