### ISSUE TITLE
Reviews being added to stage cause a timeout

### ISSUE THREAD

**Issue by andymckay** [mozilla/olympia#943]
Go to any add-on click, write a review, complete form and write a review. Click submit.

I am consistently getting: [HTTP/1.1 502 Bad Gateway 32678ms] back.

According to @jasonthomas "it seems like update_denorm is taking a while to run on stage".

**Comment by andymckay** [comment]
Also see an issue in the selenium tests: https://github.com/mozilla/olympia/issues/913

**Comment by krupa** [comment]
https://sentry.prod.mozaws.net/operations/olympia-stage/group/152130/

**Comment by andymckay** [comment]
According to @jasonthomas "943 is fixed on stage". Verified, looks good to me.

**Comment by stephendonner** [comment]
Can confirm! <webqatestbot> Project amo.stage.saucelabs build #607: FIXED in 4 min 50 sec: https://webqa-ci.mozilla.com/job/amo.stage.saucelabs/607/

**Comment by vcarciu** [comment]
Verifed as fixed
