### ISSUE TITLE
Migrate docker dev-env to Centos7

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/olympia#952]
We want to move off the old centos6-based marketplace base image and Centos 7 is what we are running in production. Also python 2.7 is already available under that without needing our own pkg.

This is a blocker for getting hold of a new node package to support running addons-validator on production as any new node packages will only get built for centos7. The ops bug related to that is here [1]

A base image repo is here: https://github.com/mozilla/addons-base - this is already being built on the docker hub. It needs anything missing adding to it and then we should get the olympia dockerfile updated to be able to use that as a base.

[1] http://bugzilla.mozilla.org/show_bug.cgi?id=1226533

**Comment by muffinresearch** [comment]
@cgrebs assigning this to you as you were interested in doing this - feel free to shout if I can lend a hand.

**Comment by EnTeQuAk** [comment]
Merged to master in https://github.com/mozilla/olympia/commit/d17f1461c7a217845aae6152ef19ba99d53fe538
