### ISSUE TITLE
Handle multiple versions in signing API

### ISSUE THREAD

**Issue by mstriemer** [mozilla/olympia#953]
https://sentry.prod.mozaws.net/operations/olympia-prod/group/153985/

There can be multiple versions for the same add-on version string if the add-on goes into the listed queue and a new file is uploaded before it is reviewed.

We should check the editor tools to see how the "active" version is selected.

**Comment by kumar303** [comment]
If they are using `jpm sign` then I think https://github.com/mozilla-jetpack/jpm/issues/386 will fix it. I'm working on that now.

**Comment by kumar303** [comment]
> If they are using jpm sign then I think mozilla-jetpack/jpm#386 will avoid this at least for jpm usage. 

we don't think this will actually be a work around so nevermind
