### ISSUE TITLE
"Duplicate add-on ID" error when trying to upload a new version of an existing unlisted addon

### ISSUE THREAD

**Issue by minj** [mozilla/olympia#961]
```sh
$ curl -w "Status: %{http_code}\\n" \
      "https://addons.mozilla.org/api/v3/addons/${AMO_WEB_ID}/versions/${VERSION}/" \
      -XPUT --form "upload=@${SRC_DIR}/${AMO_WEB_ID}.xpi" \
      -H "Authorization: JWT $(dist/amo_jwt.py)" -o response.json
Status: 400
```
response.json:
```json
{"error": "Duplicate add-on ID found."}
```

dist/amo_jwt.py:
```python
#!/usr/bin/env python
from __future__ import print_function

import time, random, jwt

from AMO.Credentials import JWT_ISSUER, JWT_SECRET

def make_token():
    now = int(time.time())
    payload = {
        'iss': JWT_ISSUER,
        'jti': str(random.random()),
        'iat': now,
        'exp': now + 60,
    }
    return jwt.encode(payload, JWT_SECRET, algorithm='HS256')

if __name__ == '__main__':
    token = make_token()
    print(token.decode(), end='')
```

iss tried:
```python
JWT_ISSUER = 'user:11864932:338' # role=developer #1
JWT_ISSUER = 'user:2425893:633' # role=owner #3
```
Submitting the same xpi via web interface works just fine

Perhaps the problem arises because iss does not belong to the original owner of the add-on listing? Unfortunately, that account is no longer accessible. Moving owner \#3 to the top of the owners list did not help.

**Comment by minj** [comment]
Apparently `https://addons.mozilla.org/api/v3/addons/${AMO_WEB_ID}/versions/${VERSION}/` returns 404

Something is definitely wrong here.

**Comment by minj** [comment]
Side note: my addon was converted listed (preliminary) -> unlisted.

**Comment by andymckay** [comment]
Just to check ${AMO_WEB_ID}, is guid of your addon?

**Comment by minj** [comment]
To be honest I didn't see `guid` actually explained anywhere.

I took it to be the 'name' of the addon in AMO's URLs, e. g.
`https://addons.mozilla.org/en-US/developers/addon/${AMO_WEB_ID}/versions`

I tried `<em:id>` from install.rdf as well but that did not work either. I think that's what you call `uuid`.

**Comment by andymckay** [comment]
No, we use the guid, because the GUID is unique outside of AMO. In other words, you can make your add-on and do a PUT into AMO without have to do an upload first, if your add-on doesn't exist, we just create it for you automatically. It's pretty neat. We should probably spell that out more in the docs: 

http://olympia.readthedocs.org/en/latest/topics/api/signing.html#put--api-v3-addons-[string-add-on-guid]-versions-[string-version]-

In your case its this `<em:id>` https://github.com/minj/foxtrick/blob/master/install.rdf#L6, there's more than one in your `install.rdf`.

**Comment by minj** [comment]
Yes, I know. Others are browser IDs.

Here is what the problem is: `https://addons.mozilla.org/api/v3/addons/{9d1f059c-cada-4111-9696-41a62d64e3ba}/versions/0.16.1/` returns
```json
{"error": "Could not find addon."}
```

While `https://addons.mozilla.org/api/v3/addons/foxtrick-light@foxtrick.org/versions/0.16.1/` is `Status: 200`

The difference between them? The latter one is a relatively new unlisted submission to AMO made after the signing was introduced. The former was converted from listed (preliminary) to unlisted and has a long history.

**Comment by mstriemer** [comment]
The GUID needs to be URL encoded so the URL should be: `https://addons.mozilla.org/api/v3/addons/%7B9d1f059c-cada-4111-9696-41a62d64e3ba%7D/versions/0.16.1/`.

**Comment by minj** [comment]
Ah, so it should. I somehow was sure curl handles that automatically.

Thank you for the help

**Comment by mstriemer** [comment]
I remember running into this early on and assuming the same thing and being surprised. I'll add a note to the docs.

**Comment by minj** [comment]
@mstriemer apparently curl supports `[]` and `{}` globs causing the problem with old-style add-on IDs. `curl -g` disables them and the braces are then correctly urlencoded.

**Comment by mstriemer** [comment]
Ahha, awesome! I'll add that to the docs. Thanks!
