### ISSUE TITLE
No uploaded file for that addon and version.

### ISSUE THREAD

**Issue by FilaBaraGit** [mozilla/olympia#972]
Hi,

I would like to use your API but I am having troubles using it. I cannot get the status of my uploaded .xpi. 
I can see the version and xpi of my addon on:
https://addons.mozilla.org/en-us/developers/addon/my_addon_uuid/versions/xxxxx

1) I uploaded the .xpi manually. 
2) I use the script to generate JWT token 

var jwt = require('jsonwebtoken');
var issuedAt = Math.floor(Date.now() / 1000);
var payload = {
  iss: 'user:...,
  jti: Math.random().toString(),
  iat: issuedAt,
  exp: issuedAt + 60,
};

var secret = '...';  // store this securely.
var token = jwt.sign(payload, secret, {
  algorithm: 'HS256',  // HMAC-SHA256 signing algorithm
});
console.log(token);

3) Then I try to get the status of my version

token=$(node test.js)
curl -v  https://addons.mozilla.org/api/v3/addons/my_addon_uuid/versions/x.x.x/ -H "Authorization: JWT $token"

4) The output is:
< HTTP/1.1 404 NOT FOUND
< Allow: GET, PUT, HEAD, OPTIONS
< Content-Type: application/json
< Date: Wed, 25 Nov 2015 12:01:19 GMT
* Server nginx is not blacklisted
< Server: nginx
< Strict-Transport-Security: max-age=31536000
< Vary: Accept, X-Mobile, User-Agent
< X-Frame-Options: DENY
< Content-Length: 57
< Connection: keep-alive
< 
* Connection #0 to host addons.mozilla.org left intact
{"error": "No uploaded file for that addon and version."}

Could you please help me?? Thanks in advance...

**Comment by andymckay** [comment]
Can I check what your addon_uuid is? For example, we recently found that curl has an issue with some add-on ids eg: https://github.com/mozilla/olympia/issues/961

**Comment by FilaBaraGit** [comment]
It is wrc@avast.com.

2015-11-25 19:18 GMT+01:00 Andy McKay <notifications@github.com>:

**Comment by FilaBaraGit** [comment]
I think the problem is that my addon is unlisted, so it is not distributed on https://addons.mozilla.org. 
So if you try: 
curl -v https://addons.mozilla.org/api/v3/addons/...

it finds your addon because it is there but the version uploaded is unlisted thus not not distributed. Am I right?

**Comment by andymckay** [comment]
Your addon is unlisted, but the API should return a value, did this work for you?

**Comment by FilaBaraGit** [comment]
Yes, it worked after a while (week or so). You have probably fixed
something. Thanks again.

2016-01-04 20:45 GMT+01:00 Andy McKay <notifications@github.com>:
