### ISSUE TITLE
Get the user's authentication source

### ISSUE THREAD

**Issue by mstriemer** [mozilla/olympia#983]
Provide an API endpoint to retrieve the user's authentication source. This should work off an email address and return `amo` or `fxa`. This will be used to determine where to send the user at login or registration time during the migration.

If the user has not migrated:
```
GET /api/v3/accounts/source/?email=not-migrated@example.com

HTTP/1.1 200 OK
Content-type: application/json

{"source": "amo"}
```

If the user has migrated:
```
GET /api/v3/accounts/source/?email=migrated@example.com

HTTP/1.1 200 OK
Content-type: application/json

{"source": "fxa"}
```

If the account doesn't exist:
```
GET /api/v3/accounts/source/?email=no-account@example.com

HTTP/1.1 200 OK
Content-type: application/json

{"source": "fxa"}
```

**Comment by andymckay** [comment]
Should we document this API? It's only going to last the length of the migration I believe.

**Comment by mstriemer** [comment]
I don't think so. It should be pretty much internal use only.
