### ISSUE TITLE
Create an interstitial to send the user to the right login source

### ISSUE THREAD

**Issue by mstriemer** [mozilla/olympia#985]
When the user clicks login or register send them to a page that asks for their email address and redirects them to the AMO login or the FxA login.

Bonus points for doing this on the regular login page and hiding the password field unless they need to do an AMO login.

<img width="461" alt="screenshot 2015-11-26 14 27 41" src="https://cloud.githubusercontent.com/assets/211578/11430287/e29492e0-9449-11e5-9c06-2d3190c6fe54.png">

**Comment by andymckay-limited-access** [comment]
Depends upon #983
