### ISSUE TITLE
Congratulate the user on successfully migrating

### ISSUE THREAD

**Issue by mstriemer** [mozilla/olympia#988]
We should tell the user how awesome they are for migrating their account. Cause they are.

<img width="580" alt="screenshot 2015-11-26 14 28 33" src="https://cloud.githubusercontent.com/assets/211578/11430302/1000938c-944a-11e5-9463-d3b4cb407648.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF44(Win 7).
Postfix screenshot:
![2016-02-05_1723](https://cloud.githubusercontent.com/assets/15685960/12850424/4f35c41c-cc2d-11e5-811f-dae316a5c4dc.png)
