### ISSUE TITLE
Improve the platform warning for WebExtensions

### ISSUE THREAD

**Issue by andymckay** [mozilla/olympia#993]
If you upload a WebExtension add-on before hand you get:

![screenshot 2015-11-27 10 04 18](https://cloud.githubusercontent.com/assets/74699/11446633/87e17ce6-94ee-11e5-8314-daabc39f3306.png)

Afterwards you get:

![screenshot 2015-11-27 10 05 24](https://cloud.githubusercontent.com/assets/74699/11446634/8da44096-94ee-11e5-834a-b456bbc5da0e.png)

Therein we lead into a complicated question of what we should show there and how WebExtensions work with platforms.

**Comment by andymckay** [comment]
cc'ing @designakt

**Comment by anaran** [comment]
What's the complication? We don't know the value of *some*?

 - [ ] Firefox OS

also needs to get into that list (sooner or later).

I can already install the  examples below, but only borderify and page-to-extension-messaging work there.

See paragraph three in https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Examples

**Comment by andymckay** [comment]
https://mail.mozilla.org/pipermail/dev-addons/2015-November/000186.html, further is Firefox OS a platform or an application?

**Comment by andymckay** [comment]
But basically, shouldn't a WebExtension work on all platforms? If so, why show this?

**Comment by designakt** [comment]
Our current approach in the redesign of the submission flow it to separate upload and platform selection.
https://www.lucidchart.com/documents/view/e8578542-dbaa-4e2e-acbe-9a8b645dde24
This way one does not see different states of the same selection UI, which I assume is is the confusing part here. cc'ing @brampitoyo as he is currently working on this topic (AMO Developer UX)

**Comment by andymckay** [comment]
I think the thread on mailing list is pointing us to the fact that for the moment, add-ons can be limited to platform. I think we'll have to leave that alone for the moment. Although removing the red warning would be nice.
