### ISSUE TITLE
Duplicated versions are created by the signing API

### ISSUE THREAD

**Issue by piroor** [mozilla/olympia#996]
Steps to reproduce:

 1. Upload a new version via the web UI (developer hub), ex. "1.5"
 2. Try to sign the same file via the signing API ( https://olympia.readthedocs.org/en/latest/topics/api/signing.html )

Expected result:

 * The API returns an error like "already registered version" or something.

Actual result:

 * The version (ex. "1.5") is duplicated on the list of "Status & Versions" on the developer hub.

Additional information:

I've tried to sign the file with my helper scripts:
https://github.com/piroor/makexpi/blob/master/get_token.sh
https://github.com/piroor/makexpi/blob/master/sign_xpi.sh

**Comment by piroor** [comment]
I've seen this problem on the addon "Reload on Idle", the id is "reload-on-idle@clear-code.com".
https://addons.mozilla.org/en-US/firefox/addon/reload-on-idle/

**Comment by mstriemer** [comment]
Perhaps the version isn't being set on the `FileUpload` that gets created when using the web interface.

**Comment by kumar303** [comment]
I can't reproduce this when following the steps as described. I get an error as expected:
````
JPM [error] Server response: Version already exists. ( status: 409 )
````
Are you sure that you fully uploaded a new version on the web UI and that it was valid? If there was a validation error, it would not have been added.

**Comment by piroor** [comment]
Here is a screenshot. Both duplicated versions have their own files.

![duplicated](https://cloud.githubusercontent.com/assets/70062/11481336/3013cc72-97e0-11e5-8490-b4aa79f9d6c8.png)

**Comment by piroor** [comment]
They are disabled by Mozilla, because AMO editor does it. When I initially uploaded the version 1.5, the first one was passed the validation and waiting review. After I got a mail from AMO editor, I realized that there are duplicated entries.

**Comment by mstriemer** [comment]
Does uploading a new file with the same version normally just update the old version? I assumed this was working as expected. Perhaps @magopian knows more on how this works.

**Comment by magopian** [comment]
Nope, there's no "update a version" feature, that I know of. You can manually remove a file from a version and re-upload it, or remove a version and re-create it, but no "automatic updating if the version number is the same" (if that's your question).

I think there's a verification done when you try creating a new version with the same version number as a previous version, when using AMO. Not sure this verification is made when going through the signing API. Maybe that's what's missing?

Are we sure it makes sense to enforce this restriction? The only downside of having the same version number might be that the newer version won't be picked up by the automatic update mechanism, but I think this isn't the case, and the latest uploaded version would still correctly be offered as an update.

**Comment by kumar303** [comment]
> The only downside of having the same version number might be that the newer version won't be picked up by the automatic update mechanism

That would be a pretty big deal. Imagine an add-on with a serious security issue that someone thought they patched but did not because the clients never auto-updated to it.

Thanks for the screenshots. It looks like a legitimate bug, now we just have to figure out how to reproduce it.

**Comment by magopian** [comment]
For the time being, I'd recommend doing the check or enforcing the restriction as it's being done on the frontend, but I'm pretty sure it's useless (and maybe harmful?). Maybe we'll find some time to discuss that at Orlando?

**Comment by kumar303** [comment]
The signing API already checks for existing versions. The bug filed here is not reproducible for me so I guess there is something more subtle happening.

**Comment by mstriemer** [comment]
I believe what the API tries to do is:

* If this version exists and has passed review reject the upload.
* If this version exists but it hasn't passed review accept the upload.
* If this version doesn't exist accept the upload.
* When an upload passes validation and it is the newest upload, create a version for it.

So you would be able to submit two uploads at the same time and they would both be "accepted" but the newest upload should supersede the older one eventually. So if you created a version by uploading through the website and it was awaiting manual review then you could still upload a new version through the API.

**Comment by kumar303** [comment]
> if you created a version by uploading through the website and it was awaiting manual review then you could still upload a new version through the API.

Okay, I just tried this locally with my Olympia instance and can confirm that it's true.

However, I also created a new add-on, made it public / listed, uploaded a new version through the web UI, used the editor tools to *approve* that version, and tried to push that same version through the signing API. I got the 'version already exists' error as expected.

Thus, this bug is limited to add-on versions awaiting approval which makes it less critical to fix.

**Comment by piroor** [comment]
Thank you for researching. FYI, when I saw this problem the status of my addon "Reload on Idle" was:

 * Newly registered recently, and not passed the full review yet. (I was trying to pass it.)
 * There were existing preliminary reviewed versions. Results of full reviews for those versions were "rejected".
 * Automatic validation didn't detect any fatal error which blocks uploading of a new version.
 * It required manual preliminary review by editors to be published.
 * In old versions I saw unknown validation error for this addon, filed at: https://bugzilla.mozilla.org/show_bug.cgi?id=1226071 (It is possibly related to this problem. I never saw such an error for my other addons.)

**Comment by kumar303** [comment]
I suppose the thing we want to fix here is not put multiple versions in the reviewers' queue. Each new upload should probably deactivate the old versions so that the reviewers only have to look at the latest one.

**Comment by retorquere** [comment]
@kumar303 but please only do this for manual review. I submit unique version numbers for debug builds and last-wins would mean I'd have to force these to serialize.

**Comment by retorquere** [comment]
BTW I've just submitted two files by API with the same version number on purpose and both were signed and appear in the UI separately, showing the same version number.

**Comment by kumar303** [comment]
This was fixed in https://github.com/mozilla/olympia/pull/1028
